### ISSUE TITLE
Can't built the string index of the Milvus 2.1.4

### ISSUE THREAD

**Issue by icodersky** [zilliztech/attu#103]
**Describe the bug:**

The string index of Milvus 2.1.4 has not been built. My table is empty. Neither ATTU nor Python code can build the string index normally. I have been waiting. The database files are growing continuously, but we haven't put data yet. (Installed by the k8s helm, the helm has updated milvus to the latest version.). The index of vectors can be builted normally.

**Steps to reproduce:**
1.
2.
3.

**Attu version:**
attu:v2.1.4
milvus:v2.1.4

![image](https://user-images.githubusercontent.com/86787724/194681531-39fafad1-8214-4f65-a0c0-c6dc653192f6.png)

**Comment by ICLzhang** [comment]
@nameczz

**Comment by nameczz** [comment]
If neither attu nor pymilvus can build string index, you should open an issue in milvus repo. 
Better to provide more logs to help reproduce.
Thanks @icodersky

**Comment by icodersky** [comment]
**This is logs.**

[milvus-log.tar.gz](https://github.com/zilliztech/attu/files/9740629/milvus-log.tar.gz)

**Comment by icodersky** [comment]
And had opened an new issue in milvus repo.

https://github.com/milvus-io/milvus/issues/19655

**Comment by icodersky** [comment]
We found a problem.
The problem occurred when we used attu2.1.1, but the problem did not occur when we used attu2.1.0

**Comment by shanghaikid** [comment]
fixed in the latest version  https://github.com/zilliztech/attu/releases/tag/v2.1.2
