### ISSUE TITLE
I got error when I upgrade attu from 2.1.2 to 2.1.4

### ISSUE THREAD

**Issue by dzqoo** [zilliztech/attu#118]
**Describe the bug:**
When I upgrade attu from 2.1.2 to 2.1.4 with Milvus2.1.2, I can't use the "Data  Preview" tab to get sample data.And I got the following    error "Type allow all->0 inmemory->1"

![image](https://user-images.githubusercontent.com/8862305/201016654-5ff3bcf2-ae83-4116-a628-bd1d6f8cac15.png)

The other information:
1. collection is loaded and can be searched with sdk the attu；
2. collection's index is hnsw and is created after all data is inserted.

**Steps to reproduce:**
1.
3.
4.

**Attu version:**
2.1.3 

**Attu version:**

**Comment by dzqoo** [comment]
attu version is 2.1.4

**Comment by shanghaikid** [comment]
dupe https://github.com/zilliztech/attu/issues/121
