### ISSUE TITLE
search 500 Error: Type allow all->0 inmemory->1

### ISSUE THREAD

**Issue by LvanLiang** [zilliztech/attu#121]
**Describe the bug:**

collection data preview error

![image](https://user-images.githubusercontent.com/11864070/202069628-45f30498-167c-4952-aad2-124d3726f090.png)

**Steps to reproduce:**
1.
2.
3.

**Attu version:**
v2.1.4

**Attu version:**

**Comment by shanghaikid** [comment]
what is your milvus version?

**Comment by LvanLiang** [comment]
> what is your milvus version?

v2.1.4

**Comment by shanghaikid** [comment]
does this feature work on the new created collection?

**Comment by yyyreal** [comment]
There is bug: 
When defining a collection, if the field of type float vector is not the second field of the schema, then the above bug will occur in Attu



Scenario 1
```python
    feature_id = FieldSchema(name="feature_id", dtype=DataType.INT64, is_primary=True, auto_id=True)
    object_feature = FieldSchema(name="object_feature", dtype=DataType.FLOAT_VECTOR, dim=512)
    filename = FieldSchema(name="filename", dtype=DataType.VARCHAR, max_length=300)

    schema = CollectionSchema(
        fields=[feature_id, object_feature, filename],
        description="TestFeature"
    )
```

Scenario 2
```python
    feature_id = FieldSchema(name="feature_id", dtype=DataType.INT64, is_primary=True, auto_id=True)
    filename = FieldSchema(name="filename", dtype=DataType.VARCHAR, max_length=300)
    object_feature = FieldSchema(name="object_feature", dtype=DataType.FLOAT_VECTOR, dim=512)

    schema = CollectionSchema(
        fields=[feature_id, object_feature, filename],
        description="TestFeature"
    )
```

Scenario 1 and 2 are the same，but Attu(2.1.4) failed to process data preview when using Scenario 2.

**Comment by shanghaikid** [comment]
> 

Sounds Interesting, we will test it soon, thanks.

**Comment by yyyreal** [comment]
Nice work. Thanks!
