### ISSUE TITLE
请问Create user目前无法使用吗？

### ISSUE THREAD

**Issue by caohangabc** [zilliztech/attu#122]
![image](https://user-images.githubusercontent.com/35301893/202342090-7140446f-2a62-4acb-9362-658b8022746d.png)

**Comment by shanghaikid** [comment]
What is your milvus version?

**Comment by caohangabc** [comment]
> What is your milvus version?

v2.0.1

**Comment by caohangabc** [comment]
I tried v2.1.4,  now it's ok， but  what is old password?

**Comment by shanghaikid** [comment]
If there is no password set, no password need.

**Comment by caohangabc** [comment]
> If there is no password set, no password need.

No, I cant't update the root password with no old password.
I use this command to start "docker run -p 8000:3000  -e MILVUS_URL={your machine IP}:19530 zilliz/attu:latest",  this mode can support TLS ,USER and password,  I can't find any help in doc

**Comment by nameczz** [comment]
@caohangabc https://milvus.io/docs/v2.1.x/authenticate.md#Create-an-authenticated-user may be can resolve you question

**Comment by caohangabc** [comment]
ok， thank you
