### ISSUE TITLE
Incorrect Datatype Errpr

### ISSUE THREAD

**Issue by dee-corr** [zilliztech/attu#126]
**Describe the bug:**
My searches are failing due to the nprobe paramter being the incorrect datatype. No matter what number I enter it fails with this error.

**Steps to reproduce:**
1. Search on binary vector data (I used 1024 dim vector) with BIN_IVF_FLAT index
2. Use the metric type TANIMOTO
3. Set nprobe to any valid number, e.g. 1 or 200

**Attu version:**
2.1.5 - but this issue was occurring for me in other recent versions

**Milvus version:**
2.2.0

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/51026617/204527511-ebfaed06-a374-4291-80b9-405ac315af46.png">

<img width="1676" alt="Screenshot 2022-11-29 at 12 21 00" src="https://user-images.githubusercontent.com/51026617/204529166-0a6e5e26-9981-4d26-9a19-348c07d4e78c.png">

**Comment by shanghaikid** [comment]
could you try attu v2.2

**Comment by dee-corr** [comment]
I updated and no change, the issue is still happening:

<img width="1775" alt="image" src="https://user-images.githubusercontent.com/51026617/204814007-4568c411-21be-4e83-9a1f-921be5cba86c.png">

**Comment by dee-corr** [comment]
Just another note. I loaded the dataset with BIN_FLAT, it doesn't cause an error but it seems that nprobe should be disabled in this case:

![image](https://user-images.githubusercontent.com/51026617/204850756-af253b4d-9f8c-4cd1-b404-62d0c4f3166c.png)

**Comment by shanghaikid** [comment]
Thanks, we'll investigate this issue soon.

**Comment by yanliang567** [comment]
@binbinlv did we meet this issue in milvus ci?

**Comment by binbinlv** [comment]
> 2\. TANIMOTO

No, the case is good on milvus side.

**Comment by binbinlv** [comment]
> @binbinlv did we meet this issue in milvus ci?

No, the case is good on milvus side.

**Comment by shanghaikid** [comment]
Yeah, this is attu issue. we will fix it today.

**Comment by dee-corr** [comment]
Thank you!!
