### ISSUE TITLE
attu 不能创建FLAT索引

### ISSUE THREAD

**Issue by wlj521** [zilliztech/attu#127]
1：Filter中根据条件搜索，范围太大了就搜索不出来，能不能加个limit条件
2：不能创建FLAT索引，按钮灰的
3：预览数据是否可以做到排序

**Comment by wlj521** [comment]
版本 v2.2.0

**Comment by shanghaikid** [comment]
Thanks, we will fix these issues in the next release.

**Comment by shanghaikid** [comment]
https://github.com/zilliztech/attu/pull/128
