### ISSUE TITLE
Helm Chart of attu and milvus

### ISSUE THREAD

**Issue by migroskub** [zilliztech/attu#13]
**Describe the feature:**
I'd like to use both Milvus and Attu with minimal fuss. Helm chart is the solution.

**Describe a specific use case for the feature:**
Test cases and fast local experiments, as well as easier production usage.

**Comment by nameczz** [comment]
@migroskub 
We have doc about how to use helm chart to install Attu and Milvus. 
https://milvus.io/docs/v2.0.0/attu_install-helm.md
Any more questions is welcome!
