### ISSUE TITLE
Unable to connect to Milvus-2.2.0 with Attu 

### ISSUE THREAD

**Issue by akmalmasud96** [zilliztech/attu#132]
**Describe the bug:**
I was installing the Milvus with attu using helm. Previously, in the version Milvus-2.1.4, there was no issue faced, but in Milvus-2.2.0, there is no option for the username and password and thus I cannot connect to Milvus through a graphical interface with the Milvus.
I have tested this with both attu version of 2.1.0 and 2.2.0. But the behavior is same.

**Steps to reproduce:**
I have been following this documentation https://milvus.io/docs/attu_install-helm.md 

Following is the error that appears, when tried to connect.
![image](https://user-images.githubusercontent.com/26347692/206203558-712a4d1f-3f0a-4f7b-877d-0a93b72ad071.png)

**Comment by shanghaikid** [comment]
https://github.com/zilliztech/attu/pull/138
