### ISSUE TITLE
attu的 Entity Count好像不太准确

### ISSUE THREAD

**Issue by wlj521** [zilliztech/attu#133]
**Describe the bug:**

删除了一批向量后，attu上面显示的还是未删除的数量，并且插入后还在增长

**Attu version:**
v2.2.0

**Comment by shanghaikid** [comment]
是的，milvus 删除后会有一段时间的等待，需要手动刷flush才会更新，这个是milvus决定的。 

attu v2.2.1 我们会把entity count 改成 approx entity count。
