### ISSUE TITLE
attu search got param error 

### ISSUE THREAD

**Issue by dzqoo** [zilliztech/attu#139]
**Describe the bug:**

When I search in attu, I got the following error message:

<img width="887" alt="89a09e84f57f91b196f4f031e322fe0" src="https://user-images.githubusercontent.com/8862305/206439174-d60926ee-94f4-4124-bcc1-4e6a18bb4bf3.png">

**Steps to reproduce:**
1.
2.
3.

**Attu version:**
V 2.2.0

**Comment by shanghaikid** [comment]
I think this was fixed in v2.2.1.
