### ISSUE TITLE
invaild wire type 7 at  offset 382

### ISSUE THREAD

**Issue by tgk60w** [zilliztech/attu#141]
**Describe the bug:**

<img width="742" alt="965b5be3f0804be1c6ef3a10052deba" src="https://user-images.githubusercontent.com/49012823/207312382-5aa77142-f825-4109-9dd2-1db45e582753.png">

**Steps to reproduce:**
1.
2.
3.

**Attu version:**

2.1.1
**Attu version:**

**Comment by shanghaikid** [comment]
What is your milvus version?
