### ISSUE TITLE
Error: Error: 14 UNAVAILABLE: Name resolution failed for target dns:{0.0.0.0}:8053

### ISSUE THREAD

**Issue by laomagic** [zilliztech/attu#153]
Error: Error: 14 UNAVAILABLE: Name resolution failed for target dns:{0.0.0.0}:8053

run code:
sudo docker run -d -p 8054:3000 -e HOST_URL=http://{127.0.0.1}:8054 -e MILVUS_URL={127.0.0.1}:8053 zilliz/attu:latest

**Comment by nameczz** [comment]
Please try sudo docker run -d -p 8054:3000 -e HOST_URL=http://175.102.135.140:8054 -e MILVUS_URL=175.102.135.140:8053 
zilliz/attu:latest @laomagic
