### ISSUE TITLE
[Feature request]Add Bookmark feature to the milvus login modal

### ISSUE THREAD

**Issue by Leslie-Wong-H** [zilliztech/attu#162]
**Describe the feature:**

Add **_Bookmark_** feature to the Milvus login modal, so users need not go elsewhere and paste their IP every time they get logged out.

**Describe a specific use case for the feature:**

Refactor this login UI and enable users to click just one button to log in to their bookmarked Milvus IP. 
![image](https://user-images.githubusercontent.com/27696701/209607644-d332d742-0779-4ea4-bd03-279dfa26b0c1.png)

**Comment by shanghaikid** [comment]
Actually , with attu v2.2.2, when you log out, your ip will be kept in the address bar.  Please try it.

**Comment by shanghaikid** [comment]
![image](https://github.com/user-attachments/assets/60246dd7-f1e9-4344-beb2-ce75f86f6c80)
