### ISSUE TITLE
attu load trie index failed.

### ISSUE THREAD

**Issue by JulyMood** [zilliztech/attu#163]
**Describe the bug:**

**Steps to reproduce:**
1.  Create trie index
2. Open attu view, Selective index schema
3.  Column "Index Type" always loaded

**Attu version: 2.1.1

**Milvus version: 2.2.2

image:
![image](https://user-images.githubusercontent.com/16485777/217477803-a84255f6-e6c9-4307-b629-38a5715e0b20.png)

![image](https://user-images.githubusercontent.com/16485777/217477906-8017dd27-6c71-492e-b8ef-5510b68e3357.png)

**Comment by kms9** [comment]
![image](https://user-images.githubusercontent.com/6856643/230601628-2a0cb703-e466-43e4-905b-b606e0ea0aa3.png)
![image](https://user-images.githubusercontent.com/6856643/230601657-4fbef451-8913-4664-a5dd-1ea572e67362.png)
使用v2.2.4  也遇到了这个问题

**Comment by shanghaikid** [comment]
> ![image](https://user-images.githubusercontent.com/6856643/230601628-2a0cb703-e466-43e4-905b-b606e0ea0aa3.png) ![image](https://user-images.githubusercontent.com/6856643/230601657-4fbef451-8913-4664-a5dd-1ea572e67362.png) 使用v2.2.4 也遇到了这个问题

You should load the collection first.
