### ISSUE TITLE
Unable to login (unknown method CheckHealth

### ISSUE THREAD

**Issue by medo-mi** [zilliztech/attu#166]
**Describe the bug:**
Unable to login using the Attu 2.2.3 gettign an error

`{"statusCode":400,"message":"Error: Error: 12 UNIMPLEMENTED: unknown method CheckHealth for service milvus.proto.milvus.MilvusService","error":"Bad Request"}`

**Steps to reproduce:**
1.
2.
3.

**Attu version:**

**Attu version:**

**Comment by shanghaikid** [comment]
What is your milvus version?

**Comment by medo-mi** [comment]
2.2.3 .deb

**Comment by shanghaikid** [comment]
![image](https://user-images.githubusercontent.com/185051/219325084-8d25995b-880a-4434-991e-6590d94a612b.png)

We tested this feature on Milvus 2.2.2 and Milvus 2.2.3. It works. 

Please double confirm your Milvus server.

**Comment by medo-mi** [comment]
I'm using Milvus 2.1.4.
I tried to connect using Attu 2.2.3 but unable to connect, so now i
downgraded to Attu 2.2.2

**Comment by shanghaikid** [comment]
> 

Yeah, the new checkHealth API is only provided after Milvus v2.2.  You can stick to Attu 2.2.2. Thanks.
