### ISSUE TITLE
Can not Login

### ISSUE THREAD

**Issue by pasa13142** [zilliztech/attu#167]
Hello, thanks for this repo!
 I have milvus running on my local. I can connect it as:
```
connections.connect(
  alias="default", 
  host='0.0.0.0', 
  port='19530'
)
``` 
It is running on Docker container. I would like to access it via attu. So I run :
`docker run -p 8000:3000 -e MILVUS_URL=0.0.0.0:19530 zilliz/attu:latest`. But i can not login. 

I also created a authenticated user:

```
from pymilvus import utility
utility.create_user('test', 'test', using='default') 
```
But doesnt work on attu page.
Thanks for in advance!

With default screen to try login, no user, no password no ssl:
<img width="1646" alt="Screen Shot 2023-02-17 at 12 10 30" src="https://user-images.githubusercontent.com/56387619/219602785-9e741c55-6c71-4d2a-aeed-646f7229216e.png">

With authenticated user and pass no ssl:
<img width="1615" alt="Screen Shot 2023-02-17 at 12 11 10" src="https://user-images.githubusercontent.com/56387619/219602941-db96fa16-f62a-4c95-8ddd-95eed5ca2f50.png">

With Authenticated user and pass and ssl: 
<img width="1616" alt="Screen Shot 2023-02-17 at 12 11 41" src="https://user-images.githubusercontent.com/56387619/219603045-cd3c4b1d-1ba4-4929-be7b-3f2e345b8967.png">

**Comment by shanghaikid** [comment]
Hi, 
If you start attu from docker, that means attu server is in the container. You must promise that the milvus server can be accessed from the container(attu server).  

That means, in attu container, ```0.0.0.0``` means just the container self, not the milvus address.  

So please use your real milvus wan ip(public ip), in this case is your desktop ip, or the container internal ip instead. 
https://linuxconfig.org/how-to-retrieve-docker-container-s-internal-ip-address

**Comment by pasa13142** [comment]
That Worked! Thanks a lot. ip from ifconfig worked everything. I appreciate!
