### ISSUE TITLE
attu client session shared by users

### ISSUE THREAD

**Issue by DennisZhao168** [zilliztech/attu#169]
**Describe the bug:**
When 2 users login the same attu site. One logout, another user sees the error that the connection is gone. Seems the backend cannot tell the different client connection by the session Id.

Version
v2.2.3

**Comment by zirota** [comment]
hey, are there any updates to this? Otherwise is it possible to include in the docs with a warning that the session is shared.
Currently, users with no admin access are able to view Milvus with admin permissions if someone logs in using admin credentials in the same attu.

**Comment by shanghaikid** [comment]
> hey, are there any updates to this? Otherwise is it possible to include in the docs with a warning that the session is shared.
> Currently, users with no admin access are able to view Milvus with admin permissions if someone logs in using admin credentials in the same attu.


Would you like to contribute for this feature?
