### ISSUE TITLE
Why does attu keep hanging by itself, but when I restart k8s, it automatically recovers, and the pod is always in the running state. The following are the logs

### ISSUE THREAD

**Issue by fangxingjun** [zilliztech/attu#171]
**Describe the bug:**

**Steps to reproduce:**
1.
2.
3.

**Attu version:**
The latest version

- **Attu version:**

**Comment by fangxingjun** [comment]
[milvus-log.tar.gz](https://github.com/zilliztech/attu/files/10877999/milvus-log.tar.gz)
![image](https://user-images.githubusercontent.com/54159669/222626316-fd440f02-d4dd-4f5d-bbc6-74aeab6cf244.png)
![image](https://user-images.githubusercontent.com/54159669/222626340-1aff0705-7915-416c-9fc6-1a68393917c8.png)

**Comment by shanghaikid** [comment]
Two questions:
What's your milvus version? 
What is your data scale?

**Comment by fangxingjun** [comment]
@shanghaikid @cxie @LoveEachDay @zhuwenxing Please take a look, thank you very much

**Comment by fangxingjun** [comment]
> 

mivlus is 2.2.3

**Comment by shanghaikid** [comment]
Ok, we will investigate this issue soon. thanks.

**Comment by fangxingjun** [comment]
Excuse me, how is the progress on this issue？

**Comment by shanghaikid** [comment]
@yanliang567 Please update the progress?

**Comment by locustbaby** [comment]
hi @fangxingjun, I read the logs you posted but didn't find any wrong here
Would you mind explaining the error of attu exactly?Can't it be accessed?

**Comment by fangxingjun** [comment]
![image](https://user-images.githubusercontent.com/54159669/223310761-01c0b9f1-1892-4af3-9a71-b620634c1885.png)
May be caused by this problem，but i have no idea to solve it.

**Comment by fangxingjun** [comment]
[values_file.zip](https://github.com/zilliztech/attu/files/10905245/values_file.zip)
This is the values.yaml configuration file， maybe it help

**Comment by locustbaby** [comment]
How do you create the nodeport? by kubectl or by helm?
So, I think you can't use the milvus now ?
Can you get inside the proxy pod and test the connection again?

**Comment by fangxingjun** [comment]
kubectl edit svc my-release-milvus.

**Comment by fangxingjun** [comment]
If I use the helm command "helm upgrade my-release milvus/milvus -f values.yaml", the mivlus cluster can be normal, and then hang up automatically after a while

**Comment by locustbaby** [comment]
So, your milvus instance can be accessed but sometimes timeout?

**Comment by fangxingjun** [comment]
yes，but i cannot handle it.

**Comment by locustbaby** [comment]
> If I use the helm command "helm upgrade my-release milvus/milvus -f values.yaml", the mivlus cluster can be normal, and then hang up automatically after a while

What are you mean about the `normal`, the milvus can be connected and do some operations?

**Comment by fangxingjun** [comment]
yes, i can do operations about insert, query when it is normal.

**Comment by locustbaby** [comment]
> yes, i can do operations about insert, query when it is normal.

If it used to be normal, I think the installation is successful, so the `hanging` problem may caused by other reasons.
I saw your pods restart many times, is there any operations? Where you install the milvus cluster?
How many quotas will milvus get?

**Comment by fangxingjun** [comment]
When I modify the values.yaml file, such as modifying the number of queryNodes, I will use helm upgrade to execute it once

**Comment by locustbaby** [comment]
If there are still no data in your milvus cluster, I suggest you setup a new milvus cluster with **a new release name**, which will save your time

**Comment by locustbaby** [comment]
If the problem still happens, I suggest you allocate more quotas for milvus

**Comment by locustbaby** [comment]
and, maybe you can try to increase timeout time

**Comment by fangxingjun** [comment]
> If the problem still happens, I suggest you allocate more quotas for milvus

more memory and cpu？The milvus cluster has 2600w records is used to test, but the query time is too long, and i have not find the problem of it.

**Comment by fangxingjun** [comment]
thank u very much, i do that about grafana right now

**Comment by locustbaby** [comment]
You can increase the timeout and make some simple requests to confirm whether the milvus is alive

**Comment by fangxingjun** [comment]
just now, i have reset the milvus cluster,  and reload the collection, i find the speed is normal, i don't sure is the quantity of indexNode that i have changed causing this problem to occur

**Comment by locustbaby** [comment]
Can turn on the service monitor to help you know more clearly about the requests

**Comment by fangxingjun** [comment]
Ok, I'm going to install k8 monitoring

**Comment by locustbaby** [comment]
Is it solved？
