### ISSUE TITLE
Unable to connect to milvus

### ISSUE THREAD

**Issue by bhuvneshsaini** [zilliztech/attu#177]
Milvus version = 2.0.2
Attu version = 2.0.5

error to connect to milvus server which both are running on same machine
bad request address

**Comment by shanghaikid** [comment]
If you are using docker version, make sure the attu docker can access milvus server.

**Comment by bhuvneshsaini** [comment]
How to do that? Please give the command

**Comment by shanghaikid** [comment]
How do you install attu?

**Comment by bhuvneshsaini** [comment]
docker run -p 8000:3000 -e HOST_URL=http://0.0.0.0:8000 -e MILVUS_URL=0.0.0.0:19530 zilliz/attu:v2.0.5

**Comment by shanghaikid** [comment]
I think you can try to put the wan ip of milvus  instead of 0.0.0.0

**Comment by beginOfAll** [comment]
I installed milvus and attu in my local docker, what is the MILVUS_URL ?

localhost:19530 is not working.

**Comment by shanghaikid** [comment]
> localhost

Please use your wan ip(local ip).  not localhost. because attu server is in a docker network. if you use localhost, that means attu server's local network, not your localhost.

**Comment by lvsh2012** [comment]
> > localhost
> 
> Please use your wan ip(local ip). not localhost. because attu server is in a docker network. if you use localhost, that means attu server's local network, not your localhost.

very nice, thinks

**Comment by lvsh2012** [comment]
> > localhost
> 
> Please use your wan ip(local ip). not localhost. because attu server is in a docker network. if you use localhost, that means attu server's local network, not your localhost.

very nice, thanks

**Comment by ljNingthouja** [comment]
I had to disable my ubuntu 22.04 server firewall to connect to milvus. Because even after allowing ports I was not able to load attu page maybe I am missing something in firewall config. Guys please help me out.

**Comment by shanghaikid** [comment]
> 

where did you installed attu? if attu is installed on your server,
1. make sure the attu server has access to where the milvus is installed. 
2. make sure your computer(where you load the attu page, where you run the browser) has access to the attu server.

**Comment by 0xAsten** [comment]
> > localhost
> 
> Please use your wan ip(local ip). not localhost. because attu server is in a docker network. if you use localhost, that means attu server's local network, not your localhost.

I used `ifconfig` command and to see the docker0 innet address and it worked.
```
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:7dff:fe0b:f36e  prefixlen 64  scopeid 0x20<link>
        ether 02:42:7d:0b:f3:6e  txqueuelen 0  (Ethernet)
        RX packets 666  bytes 2274998 (2.2 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 690  bytes 70964 (70.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
