### ISSUE TITLE
Login failed after enable tls

### ISSUE THREAD

**Issue by echo-initial** [zilliztech/attu#182]
**Describe the bug:**
Login failed after enable tls
```
Error: Error: 14 UNAVAILABLE: No connection established
    at /app/node_modules/@zilliz/milvus2-sdk-node/dist/utils/index.js:22:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  expose: true,
  statusCode: 400,
  status: 400
}
POST /api/v1/milvus/connect 400 Error: Error: 14 UNAVAILABLE: No connection established

```

**Attu version:**
v2.2.4

Where does ATTU verify after enable TLS

**Comment by nameczz** [comment]
Is your milvus support tls? Can you connect milvus successfully without tls?   @echo-initial

**Comment by echo-initial** [comment]
Before enabling TLS, both pymilvus and ATTU can be successfully connected.
After enabling TLS, pymilvus can successfully connect, but ATTU connection failed.

pymilvus:
```
connections.connect(host=HOST, port=PORT, user=USER, password=PASSWORD, secure=True, client_pem_path=CLIENT_PEM_PATH
                        , client_key_path=CLIENT_KEY_PATH, ca_pem_path=CA_PEM_PATH, server_name=SERVER_NAME)
```

**Comment by agahEbrahimi** [comment]
This issue will be fixed with PR #191

**Comment by zirota** [comment]
Hello, I am facing this issue as well.

Milvus Version: v2.2.8
Attu Version: v2.2.4

I am using server side tls authentication on milvus (`tlsMode: 1`).
I believe Attu just needs a supported ca-certificate to connect to Milvus via TLS. 
Where can we specify the required certificates?

The connection guide only shows how TLS connection can be done on `pymilvus` SDK not on Attu.

**Comment by shanghaikid** [comment]
https://github.com/zilliztech/attu/pull/347

**Comment by shanghaikid** [comment]
please follow the readme to enable tls with attu.
