### ISSUE TITLE
when the index type is diskann，the data preview will not display data

### ISSUE THREAD

**Issue by qilaijun101** [zilliztech/attu#183]
**Describe the bug:**

**Steps to reproduce:**
1.when the index type is diskann，the data preview will not display data

**Attu version: 2.2.4

information:

![image](https://user-images.githubusercontent.com/14890813/231645323-b3b782ee-35dc-408e-b203-6a66ec7d10e1.png)
![image](https://user-images.githubusercontent.com/14890813/231645734-5712f7d3-1f37-4dbc-bfa0-f23889f9d4dc.png)
please check it

**Comment by shanghaikid** [comment]
it is fixed in the latest version.
