### ISSUE TITLE
[Bug]: ATTU reported 400 error, unable to log in; View the backend log, which shows that many nodes have not been successfully deployed

### ISSUE THREAD

**Issue by 1041787154** [zilliztech/attu#189]
**Describe the bug:**
After deploying a standalone Milvus through Docker Compose, it is normal to check the service status, but ATTU cannot log in. Check the backend log and it shows that node deployment failed,

**Steps to reproduce:**
1.
2.
3.

**Attu version:**
2.2.3

**Attu version:**
![image](https://github.com/zilliztech/attu/assets/15188273/4fce8cf9-bf71-4b75-9a1c-953dae8502ae)

**Comment by nameczz** [comment]
@1041787154 
It seems that attu failed to connect to milvus.
How did you fill in the milvus address input ? Please check it, localhost or 127.0.0.1 are unvalid.

**Comment by 1041787154** [comment]
> @1041787154 It seems that attu failed to connect to milvus. How did you fill in the milvus address input ? Please check it, localhost or 127.0.0.1 are unvalid.

@nameczz 
![image](https://github.com/zilliztech/attu/assets/15188273/634bd85a-c490-4c08-85ea-c13f31741d88)
The milvus address is filled in according to the normal IP address,Is there any other reason?

**Comment by flealq** [comment]
same problem! I'm using milvus 2.2.3, tried attu 2.2.5/dev, tried 127.0.0.0, localhost, and lan_ip with same result: "error: no connection established".

**Comment by 1041787154** [comment]
> same problem! I'm using milvus 2.2.3, tried attu 2.2.5/dev, tried 127.0.0.1, localhost, and lan_ip with same result: "error: no connection established".

Check if the machine where the milvus service is located has port 19530 open and if a firewall is enabled

**Comment by 1041787154** [comment]
ok
