### ISSUE TITLE
collection() function throws the exception in pymilvus 2.2.8

### ISSUE THREAD

**Issue by DennisZhao168** [zilliztech/attu#193]
**Describe the bug:**
Load the collection which was created in attu (2.2.5) failed in pymilvus 2.2.8

**Steps to reproduce:**
1. Setup a new collection in attu (2.2.5) and choose Int64 as the ID type
2.The Max-Length is NULL as the default value.
3. Tried to load the collection in pymilvus 2.2.8
4. An exception occurs 
"MilvusException(message=f"Unexpected error, message=<{str(e)}>") from e
pymilvus.exceptions.MilvusException: 
<MilvusException: (code=1, message=Unexpected error, message=<invalid literal for int() with base 10: 'null'>)>

**Attu version:**
2.2.5

**Attu version:**

**Comment by petros94** [comment]
+1

**Comment by wangxx210** [comment]
upgrade pymilvus to 2.2.14
