### ISSUE TITLE
Error: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted

### ISSUE THREAD

**Issue by weiZhenkun** [zilliztech/attu#197]
**Describe the bug:**

<img width="530" alt="a9699dc483f8ab4f1c5885db5697ca5" src="https://github.com/zilliztech/attu/assets/27683687/b04eff74-d884-4cd0-b109-b06fd626851e">

**Steps to reproduce:**
1. index more data by ***import sample data*** button in the collections page
2. make data volume to 30W
3. there will show this error message "Error: Error: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted"

**Attu version:** v 2.2.4
**Attu log**: 
![image](https://github.com/zilliztech/attu/assets/27683687/b2aa17d0-4ea1-4ae1-b354-40b466dc2017)

**Comment by zirota** [comment]
@weiZhenkun may I know what was the resolution for this? Because I am facing the same issue v2.2.4
