### ISSUE TITLE
向量数据管理

### ISSUE THREAD

**Issue by evanlong0803** [zilliztech/attu#207]
**Describe the feature:**

- 删除向量数据
- 新增导入向量数据的文件格式

**Describe a specific use case for the feature:**

- 删除指定向量数据或清空集合/分区的向量数据
- 新增导入向量数据文件格式，支持一下json文件导入数据

**Comment by evanlong0926** [comment]
每次测试的时候都是重新创建集合来删除向量，有什么更好的办法吗😂

**Comment by shanghaikid** [comment]
> 每次测试的时候都是重新创建集合来删除向量，有什么更好的办法吗😂

This pr should fix this.  you can duplicate a collection now(without data). 

https://github.com/zilliztech/attu/pull/346
