### ISSUE TITLE
JSON field unable to render in data preview.

### ISSUE THREAD

**Issue by ainilili** [zilliztech/attu#209]
**Describe the bug:**
JSON field unable to render in data preview

**Steps to reproduce:**
Collection schema:

<img width="969" alt="image" src="https://github.com/zilliztech/attu/assets/26395860/25e29c01-df36-4621-ae4b-c6100d3fbfb8">

And the data preview:

<img width="1182" alt="image" src="https://github.com/zilliztech/attu/assets/26395860/c844ce79-a207-45d9-9c94-14d54185cacc">

**Attu version:**
v2.2.7

**Comment by shanghaikid** [comment]
I may forget to change here, I will fix this later. 
If you want to view data,  you can switch to the data query page, enter id>0 in the text input, then press 'Enter'

**Comment by shanghaikid** [comment]
That's pretty weird. 
I can see the json view.  Can you show me your collection schema? 
![image](https://github.com/zilliztech/attu/assets/185051/222393c7-4969-43d2-b990-1c1accdd2e29)

**Comment by ainilili** [comment]
Okey

**Comment by shanghaikid** [comment]
https://github.com/zilliztech/attu/pull/239
