### ISSUE TITLE
Embedding collection's Data Preview - Always show no data

### ISSUE THREAD

**Issue by DennisZhao168** [zilliztech/attu#210]
**Describe the bug:**

**Steps to reproduce:**
1. Login into attu
2. Choose a collection
3. Go to Data Preview tab

**Attu version:**
2.2.7

**Comment by shanghaikid** [comment]
what is your milvus version?

**Comment by DennisZhao168** [comment]
Milvus 2.2.3

**Comment by DennisZhao168** [comment]
some Milvus 2.2.8 have the same issue.

**Comment by shanghaikid** [comment]
what's your schema?

**Comment by DennisZhao168** [comment]
Id varchar (max 255)
emb FloatVector (dim 256)
timestamp int64

**Comment by shanghaikid** [comment]
![image](https://github.com/zilliztech/attu/assets/185051/521e5fed-eaa6-4e66-ba6e-507035591f98)
![image](https://github.com/zilliztech/attu/assets/185051/12194665-8e3b-4c07-aa27-6ee94e079e2d)
I am testing with 2.2.10.  

How do you insert your data?  pymilvus? node sdk? or just import sample data from attu?

**Comment by DennisZhao168** [comment]
We insert the vectors via Milvus Java SDK.

**Comment by shanghaikid** [comment]
> We insert the vectors via Milvus Java SDK.

Would you like to show me the code?

**Comment by weihaopeng** [comment]
<img width="928" alt="image" src="https://github.com/zilliztech/attu/assets/33681454/dff8a2ed-7d9d-4ce3-a1c1-446ddacd8cff">


Same problem. Attu 2.2.5, can show data. 2.2.7, show no data.

**Comment by daxiaraoming** [comment]
duplicate of #223

**Comment by shanghaikid** [comment]
> ![image](https://user-images.githubusercontent.com/116480575/280724685-89bd777a-6605-42d9-aa4c-23f7bf3d01fa.png) Embedding collection's Data Preview - Always show no data

Did you load the collection ?
