### ISSUE TITLE
vector search - result does not include the primary key

### ISSUE THREAD

**Issue by DennisZhao168** [zilliztech/attu#211]
**Describe the bug:**
When try search vectors in attu's vector search using sample embeddings, the result only includes the rank and distance, but no primary key.
url:
milvus_url?#/search?collectionName=xxx

**Attu version:**
2.2.7

**Comment by shanghaikid** [comment]
what is your schema?

**Comment by shanghaikid** [comment]
https://github.com/zilliztech/attu/pull/239
