### ISSUE TITLE
UnauthorizedError: Please connect milvus first

### ISSUE THREAD

**Issue by Bennu-Li** [zilliztech/attu#22]
**Describe the bug:**

I install attu with milvus helm chart, and i get an error like follows when connecting milvus service:
<img width="1910" alt="截屏2022-02-14 下午5 27 12" src="https://user-images.githubusercontent.com/53458891/153836681-94df23e4-5706-40d0-ad4f-a40f35028e45.png">

**Steps to reproduce:**
1. helm install attu-3 milvus/milvus --set attu.enabled=true
2. Configure DNS on my computer: xx.xx.xx.xx     milvus-attu.local
3. Visit http://milvus-attu.local 
4. connect Milvus server: http://attu-3-milvus:19530

**Attu version:**
image: zilliz/attu:latest

**Comment by nameczz** [comment]
fix in pr #23 .
Will release it today
