### ISSUE TITLE
No Data in Data Preview after upgrade from 2.2.5 to 2.2.6 or 2.2.7

### ISSUE THREAD

**Issue by daxiaraoming** [zilliztech/attu#223]
**Describe the bug:**
No Data in Data Preview, but ```Approx Entity Count``` show the correct number.
After downgrade back to 2.2.5, data appeared again.

Also while open app show the following error info if the connection was not closed last time.
```TypeError: Cannot read properties of undefined (reading 'showCollections')```
Then click close connection
```TypeError: Cannot read properties of undefined (reading 'closeConnection')```

**Steps to reproduce:**
1. Upgrade from 2.2.5 to 2.2.7
2. Open app
3. Open the Data Preview page of the old collection
4. Close Connection

**Attu version:**
2.2.6,2.2.7

**Attu version:**

**Comment by shanghaikid** [comment]
what is your milvus version

**Comment by daxiaraoming** [comment]
> what is your milvus version

v2.2.5

**Comment by shanghaikid** [comment]
> > what is your milvus version
> 
> v2.2.5

I will check soon.

**Comment by ponponon** [comment]
我也遇到了，我的 milvus 版本是 2.2.6

我的 attu 版本是 2.2.8

既不然预览数据，也无法查询数据

<img width="901" alt="图片" src="https://github.com/zilliztech/attu/assets/38725104/129f8d6d-d8b4-43e6-80c8-669a17d9d688">


<img width="1401" alt="图片" src="https://github.com/zilliztech/attu/assets/38725104/933282a8-2b3e-4117-8c68-32d33e6d5a21">

**Comment by shanghaikid** [comment]
ok, I will test it on v2.2.6.

**Comment by ponponon** [comment]
> 我也遇到了，我的 milvus 版本是 2.2.6
> 
> 我的 attu 版本是 2.2.8
> 
> 既不然预览数据，也无法查询数据
> <img alt="图片" width="901" src="https://user-images.githubusercontent.com/38725104/263627252-129f8d6d-d8b4-43e6-80c8-669a17d9d688.png"> <img alt="图片" width="1401" src="https://user-images.githubusercontent.com/38725104/263627371-933282a8-2b3e-4117-8c68-32d33e6d5a21.png">

已解决：
- 等待不解决问题
- 升级 attu 到最新的 2.2.8 不解决问题
- 把 attu 降级到 2.2.5 解决问题

我的 milvus 版本是 2.2.6
