### ISSUE TITLE
Connection Error due to SSL Option Removal

### ISSUE THREAD

**Issue by zirota** [zilliztech/attu#225]
**Describe the bug:**

Unable to connect to Milvus cluster.
Connection error (Bad Request) when connecting to Milvus cluster with server side tls enabled.

I noticed that ssl was removed on 2.2.7: https://github.com/zilliztech/attu/pull/203
May I know why was it removed? And how can we connect using SSL enabled if this is the case

**Steps to reproduce:**
1. Login to Milvus running on same Kubernetes namespace (e.g. `milvus:19530`)

Specifying `https://milvus:19530` does not work as well.

**Attu version:**
v2.2.7

**Milvus version:**
2.2.10

**Comment by shanghaikid** [comment]
Let me check it soon. `https` should be equal to `ssl:true`.
