### ISSUE TITLE
Create a collection in a specified database (not "default") successully, but found nothing in attu interface.

### ISSUE THREAD

**Issue by loche666** [zilliztech/attu#229]
**Describe the bug:**
I have created a collection using a specified database (not "default" db) successfully. 
However, I didn't find this database or collectoins in this db in attu interface. Is this a bug or how can I find this collection in the interface?

**Steps to reproduce:**
1. Using python sdk to create a db: db.create_database('llm') 
2. Using database: db.using_database('llm')
3. Creating a collection: collection = Collection(collection_name, schema, consistency_level='strong')
4. Login to attu, to find this collection or db, but not fond.

**Attu version:**
2.2.7

**Milvus version:**
2.2.12

**Comment by shanghaikid** [comment]
yeah, non-default db is not support in attu yet. We will release new version soon.

**Comment by loche666** [comment]
Thanks a lot, we are looking forward to this feature~
