### ISSUE TITLE
I can login attu GUI without username and password

### ISSUE THREAD

**Issue by islet5** [zilliztech/attu#233]
**Describe the bug:**
i can login attu console without username and password.
milvus username and password is optional, is it possible to make them required?
i already enabled authorization in helm values.yaml
<img width="533" alt="image" src="https://github.com/zilliztech/attu/assets/9824473/67ecd3cf-92d4-4b46-aae1-d8f68fe28c1f">

**Steps to reproduce:**
1.
2.
3.

**Attu version:**
zilliz/attu:v2.2.4

**Attu version:**

<img width="600" alt="image" src="https://github.com/zilliztech/attu/assets/9824473/ca7d4701-a3e8-4c9a-ae25-d4147f5b4520">

**Comment by shanghaikid** [comment]
did you create an user in milvus?

**Comment by shanghaikid** [comment]
Ok, I'll investigate this.

**Comment by islet5** [comment]
> @islet5 did you set authorizationEnabled = true in milvus.yml? ![image](https://user-images.githubusercontent.com/20559208/256563435-0dfb1ed9-2ea5-4176-9c04-afced9ebcd4f.png) https://milvus.io/docs/authenticate.md#Authenticate-User-Access

hi, yes, i added it in extraConfigFiles that i mentioned in the pic in the description of this issue

**Comment by shanghaikid** [comment]
> 

Did you restart the milvus after the modification of `milvus.yaml`? 

On my testing, `authorizationEnabled` actually works.

**Comment by ZachHandley** [comment]
Commenting because I have this issue too, I've changed my config about 20 times and it still won't work

**Comment by shanghaikid** [comment]
> Commenting because I have this issue too, I've changed my config about 20 times and it still won't work
> 
> I followed the instructions of both the `Configuring Milvus` instructions and the instructions here

Following this instruction, I can login into my server with root and the password  
1. update `milvus.yaml` set authrizationEnabled to `true`
![image](https://github.com/zilliztech/attu/assets/185051/8747863c-45e3-4b92-bb9e-a8e1a28d3e90)
2. restart your milvus server
3. use username:`root` and  password: `Milvus` to login in via attu.

**Comment by islet5** [comment]
> > Commenting because I have this issue too, I've changed my config about 20 times and it still won't work
> > I followed the instructions of both the `Configuring Milvus` instructions and the instructions here
> 
> Following this instruction, I can login into my server with root and the password
> 
> 1. update `milvus.yaml` set authrizationEnabled to `true`
>    ![image](https://user-images.githubusercontent.com/185051/262566111-8747863c-45e3-4b92-bb9e-a8e1a28d3e90.png)
> 2. restart your milvus server
> 3. use username:`root` and  password: `Milvus` to login in via attu.

can u login into server without username and password? My issue is i can log in server without username and password

**Comment by shanghaikid** [comment]
> > > Commenting because I have this issue too, I've changed my config about 20 times and it still won't work
> > > I followed the instructions of both the `Configuring Milvus` instructions and the instructions here
> > 
> > 
> > Following this instruction, I can login into my server with root and the password
> > 
> > 1. update `milvus.yaml` set authrizationEnabled to `true`
> >    ![image](https://user-images.githubusercontent.com/185051/262566111-8747863c-45e3-4b92-bb9e-a8e1a28d3e90.png)
> > 2. restart your milvus server
> > 3. use username:`root` and  password: `Milvus` to login in via attu.
> 
> can u login into server without username and password? My issue is i can log in server without username and password

if `authorizationEnabled` is true, I can login with `root` & `Milvus`, but I can't login without them. 

Looks like your attu is a little bit old, would you like to upgrade it to the latest version?  or v2.2.5 maybe.

**Comment by islet5** [comment]
> 

i upgraded it to v2.2.5, but i can still login without username/password
![image](https://github.com/zilliztech/attu/assets/9824473/d0efac0e-971f-4df0-963d-6d8af9556c71)

**Comment by shanghaikid** [comment]
what's your milvus version ? ...

**Comment by techgeniuswang** [comment]
Hi @shanghaikid @nameczz 
May I know how to setup **"common.security.authorizationEnabled": "true"** in milvus.yaml ?
I tried put it under attu.environment, but not worked as expect.

<img width="862" alt="image" src="https://github.com/zilliztech/attu/assets/31273693/f58cf343-6379-403b-9aef-de700516fafb">

Would you please guide how to correct it, many thanks.

**Comment by shanghaikid** [comment]
`common.security.authorizationEnabled` is milvus parameter, not attu's. 

you can follow this doc to change the parameter : https://milvus.io/docs/configure-docker.md

**Comment by techgeniuswang** [comment]
> `common.security.authorizationEnabled` is milvus parameter, not attu's.
> 
> you can follow this doc to change the parameter : https://milvus.io/docs/configure-docker.md

ok, got! many thanks.

@islet5 

you may put  [**common.security.authorizationEnabled: "true"**] at here:
<img width="790" alt="image" src="https://github.com/zilliztech/attu/assets/31273693/458c02e9-06ec-4648-b21c-6c7d37fa0efb">

then it worked on my side
<img width="986" alt="image" src="https://github.com/zilliztech/attu/assets/31273693/faac8f43-e48a-4591-a278-70f3d8fb1433">
