### ISSUE TITLE
attu对milvus的数据管理时效性与milvus_cli的终端查询最好可以保持一致性

### ISSUE THREAD

**Issue by Youfenghao** [zilliztech/attu#245]
**Describe the feature:**

attu在对新建向量数据表的entity count的统计最好与milvus_cli保持一致，不要出现attu看不到数据量情况，但在milvus_cli上可以查到数据量，如何过是这样的话， attu的使用价值是不大的
**Describe a specific use case for the feature:**
比如，我在milvus上新建了一个含有json字段的第三个向量索引表，然后我插入了200多条数据，希望 attu能的entity count能及时统计出我插入的200条数据，比如通过刷新按钮，可以代替我手动去milvus_cli终端查询是否已插入200多条数据

**Comment by shanghaikid** [comment]
milvus有一致性的不同设置，如果你创建collection的时候设置成strong， entity count查询出来的数字是保持一直的，但是为了性能考虑，默认的collection都是bounded。 所以会有可能会出现不一致的情况。 这个行为在milvus2.3会进行改良，2.3会在近期发布beta，所以后续会解决这个问题。 

具体可参考https://milvus.io/docs/consistency.md

**Comment by shanghaikid** [comment]
> > 
> 
> 如果我不修改一致性级别，我要等几年才能看到结果？
> 
> 我的 pymilvus 可以 query 和search，但是用 attu 看到的就是空？
> 
> 需要等今年才能在 attu 中看到？
> 
> <img alt="图片" width="1439" src="https://user-images.githubusercontent.com/38725104/263623410-15363336-d716-49d5-bc55-7c4d5e446050.png"> <img alt="图片" width="1072" src="https://user-images.githubusercontent.com/38725104/263623480-9373c4e9-993e-4422-b6f4-a25752b4dc92.png">

理论上过一段时间就可以看到，或者你试试pymilvus的flush? 
https://milvus.io/api-reference/pymilvus/v2.2.x/Collection/flush().md 

后续attu会增加在界面上flush的功能。 ：）

我感觉你这边可能是attu的bug，尝试一下升级attu到最新版试试？

**Comment by ponponon** [comment]
已解决：
- 等待不解决问题
- 升级 attu 到最新的 2.2.8 不解决问题
- 把 attu 降级到 2.2.5 解决问题

我的 milvus 版本是 2.2.6
