### ISSUE TITLE
Error: Milvus is not ready yet.

### ISSUE THREAD

**Issue by Friedrich-hue** [zilliztech/attu#249]
按照官方教程走下来，报错：

Error: Milvus is not ready yet.

**Comment by shanghaikid** [comment]
milvus 服务正在启动，可能需要等一会儿。

**Comment by Friedrich-hue** [comment]
正常大概需要多久，快30分钟了，，，

**Comment by Friedrich-hue** [comment]
> milvus 服务正在启动，可能需要等一会儿。

测试了一天，，，一直是这个同样问题

**Comment by shanghaikid** [comment]
> 正常大概需要多久，快30分钟了，，，

milvus版本，attu版本？

**Comment by CharlexChen** [comment]
这个问题是因为attu的版本太高了，降到2.2.2就好了的

docker run -p 8000:3000 -e MILVUS_URL={milvus server IP}:19530 zilliz/attu:v2.2.2

**Comment by shanghaikid** [comment]
> 这个问题是因为attu的版本太高了，降到2.2.2就好了的
> 
> docker run -p 8000:3000 -e MILVUS_URL={milvus server IP}:19530 zilliz/attu:v2.2.2

？ 你的milvus是什么版本啊？

**Comment by CharlexChen** [comment]
又或者将milvus的版本更新到v2.2或者更高

**Comment by CharlexChen** [comment]
> 

我在用milvus:v2.1.4

**Comment by Friedrich-hue** [comment]
额，，我现在换成qdrant了，，，

**Comment by Friedrich-hue** [comment]
> > 这个问题是因为attu的版本太高了，降到2.2.2就好了的
> > docker run -p 8000:3000 -e MILVUS_URL={milvus server IP}:19530 zilliz/attu:v2.2.2
> 
> ？ 你的milvus是什么版本啊？

实在没跑通，，换成qdrant了

**Comment by Samge0** [comment]
我的 milvus:v2.0.2 + attu:v2.3.1 也遇到这个问题，改为 attu:v2.2.2 就可以了

**Comment by shixiang1011** [comment]
请问解决了吗

**Comment by Friedrich-hue** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
