### ISSUE TITLE
Auto ID is not work in creation with zttu 2.3.0

### ISSUE THREAD

**Issue by JiehangXie** [zilliztech/attu#260]
**Describe the bug:**

![image](https://github.com/zilliztech/attu/assets/51190264/61105af8-837d-42df-b9e5-73e60b09e05e)

![image](https://github.com/zilliztech/attu/assets/51190264/080ebf74-318f-4009-b57d-fc3faabbb538)

Attu version:2.3.0

**Comment by shanghaikid** [comment]
what's your milvus verison？

**Comment by JiehangXie** [comment]
> what's your milvus verison？

the newest, 2.3.0

**Comment by shanghaikid** [comment]
seems like a milvus bug.

**Comment by JiehangXie** [comment]
> seems like a milvus bug.

maybe caused by zttu, when I use pymilvus to create database, it works.

**Comment by shanghaikid** [comment]
> > seems like a milvus bug.
> 
> maybe caused by zttu, when I use pymilvus to create database, it works.

Maybe they added some magic in the pymilvus that I don't know, I will investigate this.
