### ISSUE TITLE
Doc about attu installation by helm is out of date

### ISSUE THREAD

**Issue by zhuwenxing** [zilliztech/attu#27]
**Describe the bug:**
In https://github.com/zilliztech/attu#attu-doc, insight is still used rather than attu
For example
`helm install my-release milvus/milvus --set insight.enabled=true`
However in https://github.com/milvus-io/milvus-helm/blob/master/charts/milvus/values.yaml, `attu` is used as the key. 

**Steps to reproduce:**
1.
2.
3.

**Attu version:**

**Attu version:**

**Comment by nameczz** [comment]
@Bennu-li will help this

**Comment by Bennu-Li** [comment]
fixed
