### ISSUE TITLE
attu scalar indexing failed

### ISSUE THREAD

**Issue by sunwsh** [zilliztech/attu#279]
**Describe the bug:**
       I use attu/v2.2.8 to access the backend of milvus/v2.2.12, and create an index for the VarChar scalar in the management backend. The prompt: "**can only use ''Trie" when data type is VarChar**"
Even upgrading to attu/v2.3.1 still fails

**Steps to reproduce:**
1.  Select a collection and click to enter Click and select the "schema" tab.
2. Select field type=VarChar and click "+index"

**Comment by shanghaikid** [comment]
This has been fixed, but not released yet.
https://github.com/zilliztech/attu/issues/272
