### ISSUE TITLE
Using `in` or `not in` in expressions returns `cannot parse expressions` error if primary key(id) is `varchar` data type

### ISSUE THREAD

**Issue by haxung** [zilliztech/attu#281]
**Describe the bug:**
How to use query expr `in` or `not in` if primary key `id` is `varchar` data type?

If expr is `id in [12528c68-1904-43c0-b918-f64d7f64629c_6]`, then returns error like below:
![image](https://github.com/milvus-io/milvus/assets/36329819/e4857006-a00a-4a09-9dba-5a70822ab913).

Then if expr is `id in ["12528c68-1904-43c0-b918-f64d7f64629c_6"]`, then returns error like below:
![image](https://github.com/milvus-io/milvus/assets/36329819/6d2e47d1-88c2-4879-bd55-38712bb5990e)

Finally expr is `id in [\"12528c68-1904-43c0-b918-f64d7f64629c_6\"]`, then returns error like below:
![image](https://github.com/milvus-io/milvus/assets/36329819/a3d55714-65b0-48cc-ab31-feb2f32dc438)

If use go SDK, for example:

```go
......
expr := fmt.Sprintf(`id in [%s]`, `"12528c68-1904-43c0-b918-f64d7f64629c_6"`)
resultSet, err = c.Query(context.Background(), coll, nil, expr, []string{"id"})
if err != nil {
	panic(err)
}
fmt.Println(len(resultSet), resultSet.GetColumn("id").Len())
```
This returns right result.

**Steps to reproduce:**
1. This is collection schema and data csv:
![image](https://github.com/zilliztech/attu/assets/36329819/94a57c8e-4404-4d43-bfb4-84233cac98d5)
[query_result.csv](https://github.com/zilliztech/attu/files/12844691/query_result.csv)

2. Try to query data use `in` or `not in`
3. Returns error `cannot parse expressions`

**Attu version:**
v2.2.3

**Comment by shanghaikid** [comment]
would you please upgrade attu to the latest version?

**Comment by haxung** [comment]
> would you please upgrade attu to the latest version?

I will try to test the latest version attu.
