### ISSUE TITLE
when importing data through csv,  the content of varchar type with a json format will become [object Object].

### ISSUE THREAD

**Issue by yangshuai0711** [zilliztech/attu#282]
**Describe the bug:**

when importing data through csv,  the content of varchar type with a json format will become [object Object].

After checking, in attu front-end code, csv parsing library will parse a json format varchar value into an object, and the backend will handle it as a string.

**Steps to reproduce:**
1. create a Collection with a varchar field
2. make a csv file，the varchar field with values like "{""key"":123,""key2"":456}"
3. import the file into a exist partition

**Attu version:**

2.2.8

**Attu version:**

**Comment by shanghaikid** [comment]
[fixed. ](https://github.com/zilliztech/attu/pull/412)
