### ISSUE TITLE
Error: 8 RESOURCE_EXHAUSTED: grpc: received message larger than max (105700096 vs. 67108864)

### ISSUE THREAD

**Issue by ponponon** [zilliztech/attu#283]
Error: 8 RESOURCE_EXHAUSTED: grpc: received message larger than max (105700096 vs. 67108864)

<img width="1438" alt="图片" src="https://github.com/zilliztech/attu/assets/38725104/31e16041-691f-4029-9115-417c42f3a0e1">

attu 插入随机随机一多就报错：10k 不会报错，但是 50k 就会报错

attu 和 milvus 都是 2.3.1

机器是 32core cpu、128GB RAM、4TB SSD 的

**Comment by shanghaikid** [comment]
please try the latest version. if the problem is still there, please reopen the issue.
