### ISSUE TITLE
docker run happen error

### ISSUE THREAD

**Issue by fresh7849** [zilliztech/attu#300]
**Describe the bug:**
docker run -p 8000:3000 zilliz/attu:latest

node[1]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb87bc0 node::Abort() [node]
 2: 0xb87c3e  [node]
 3: 0xbf50fe  [node]
 4: 0xbf51e1 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xb458f3 node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [node]
 6: 0xb45f4b node::Start(int, char**) [node]
 7: 0x7f35fa4171ca  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f35fa417285 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xac3f4e _start [node]

![attu1](https://github.com/zilliztech/attu/assets/21075537/66ef24a4-61aa-4dd0-a552-c3df7b77a98d)
![attu2](https://github.com/zilliztech/attu/assets/21075537/30dd41da-5f88-42a4-af7a-4450e381fd07)
![attu3](https://github.com/zilliztech/attu/assets/21075537/21e36d76-afdc-4144-a5e5-27efa0de218e)

above v2.3.0 will happen error! below v2.3.0 is no problem, please check.

**Steps to reproduce:**
1.
2.
3.

**Attu version:**

**Attu version:**

**Comment by shanghaikid** [comment]
Not sure if this is the same issue: 
https://github.com/nodejs/node/issues/43064 

I will test it soon.

**Comment by raymondsryang** [comment]
Same issue
image version:
docker.io/zilliz/attu                          v2.3.1                         9097b24f157c

**Comment by shanghaikid** [comment]
> Same issue
> 
> **image version:** docker.io/zilliz/attu v2.3.1 9097b24f157c
> 
> v2.3.0 is ok

https://github.com/nodejs/node/issues/43064#issuecomment-1811525001 seems like a solution, upgrade your docker version on the host. @raymondsryang @fresh7849  .
