### ISSUE TITLE
Attu supports login password authentication

### ISSUE THREAD

**Issue by jkl0898** [zilliztech/attu#303]
**Describe the feature:**

Currently, the Attu login page does not require user password authentication to complete login and perform data operations. This poses a certain security risk when used in a production environment, as it allows any unauthenticated user to interact with production data. It would be beneficial if Attu could consider supporting user password login authentication to enhance system security and make it more suitable for production use and promotion.

**Describe a specific use case for the feature:**

In our current use case, due to the lack of user and password authentication, Attu is only used in a testing environment. We hope that the Attu team can consider adding this feature. Thank you!

**Comment by shanghaikid** [comment]
You need to enable authentication from milvus side. 

Here is the doc https://milvus.io/docs/authenticate.md .

After that, you should be able to login attu with user/password.

**Comment by jkl0898** [comment]
> You need to enable authentication from milvus side.
> 
> Here is the doc https://milvus.io/docs/authenticate.md .
> 
> After that, you should be able to login attu with user/password.

Thank you, I will have a try, and let you know the progress.

**Comment by jkl0898** [comment]
> You need to enable authentication from milvus side.
> 
> Here is the doc https://milvus.io/docs/authenticate.md .
> 
> After that, you should be able to login attu with user/password.

Hi. it works, thank you!

**Comment by jkl0898** [comment]
> > You need to enable authentication from milvus side.
> > Here is the doc https://milvus.io/docs/authenticate.md .
> > After that, you should be able to login attu with user/password.
> 
> Hi. it works, thank you!

<img width="1350" alt="image" src="https://github.com/zilliztech/attu/assets/14175165/c3fc5c38-1a95-441b-8007-eae77715331d">

By the way，when security configurations is enable,  it is not optional but necesarry.
