### ISSUE TITLE
Use the count (*) interface of query to replace the num_entities () interface

### ISSUE THREAD

**Issue by JackLCL** [zilliztech/attu#304]
**Describe the feature:**
![image](https://github.com/zilliztech/attu/assets/53512883/b2076009-dd87-48a1-854e-9a792147d651)

num_entities () interface is inaccurate, using the query count (*) interface can more accurately count the number of data.
**Describe a specific use case for the feature:**

**Comment by shanghaikid** [comment]
query count (*) is only applied on loaded collection.  may be we  can update the card in  loaded collections section.
