### ISSUE TITLE
Does Attu have an acceleration mechanism for vector search?

### ISSUE THREAD

**Issue by Howie516** [zilliztech/attu#311]
### Discussed in https://github.com/zilliztech/attu/discussions/310

<div type='discussions-op-text'>

<sup>Originally posted by **Howie516** November  9, 2023</sup>
When search vectors on the web side, it is much faster (about an order of magnitude) than using the SDK. 
Especially for HNSW vectors, this is the case for diskann indexes only for high dimensional large data volumes</div>

**Comment by shanghaikid** [comment]
No, Attu uses [milvus node sdk](https://github.com/milvus-io/milvus-sdk-node). 

No cache or other acceleration mechanism included. 

Which sdk are you testing against?
