### ISSUE TITLE
support connect to specific database

### ISSUE THREAD

**Issue by Kevinello** [zilliztech/attu#312]
**Describe the feature:**
support connect to specific database in the login interface
<img width="1306" alt="image" src="https://github.com/zilliztech/attu/assets/56342249/2b8ce40d-4d0b-4922-b06c-c99e37e6ace7">

**Describe a specific use case for the feature:**
if a user don't have privillage of ListDatabases in database 'default', then the user can't switch to the database he has privillages in
<img width="1510" alt="image" src="https://github.com/zilliztech/attu/assets/56342249/656d752c-dc53-4082-bfc7-67b7c0ff17af">

**Comment by Kevinello** [comment]
In another word, i either need a way to straight connect to specific database, or a way to do 'db.using_database("xxx")' in attu ui interface

**Comment by kish5430** [comment]
HI Team,

On the Attu login page, the 'Milvus Database' option is visible. However, after logging in, users can see a list of all databases, even those they don't have access to. They cannot view collections in databases without the necessary privileges. To enhance security, we should display only the databases that the user has access to.

Thanks

**Comment by shanghaikid** [comment]
> HI Team,
> 
> On the Attu login page, the 'Milvus Database' option is visible. However, after logging in, users can see a list of all databases, even those they don't have access to. They cannot view collections in databases without the necessary privileges. To enhance security, we should display only the databases that the user has access to.
> 
> Thanks

This is rbac problem, will fix it in another ticket.
