### ISSUE TITLE
container image on ARM Platform

### ISSUE THREAD

**Issue by STRRL** [zilliztech/attu#313]
**Describe the feature:**

Hi! Recently I have been investigating running milvus on arm machine.

It works well so far, but I have trouble with setting up attu.

attu does not provide an official arm docker container image.

I am very glad to make contribution to update the existing github action workflow to build arm container image with userspace qemu.

**Describe a specific use case for the feature:**

using milvus on arm machine

**Comment by shanghaikid** [comment]
Please make a pull request, I'm happy to merge.  :)

**Comment by kish5430** [comment]
HI Team,

Have you released the attu  arm docker container image.?

Thanks

**Comment by shanghaikid** [comment]
We have released arm image on the dev channel, you can have a try.

![image](https://github.com/zilliztech/attu/assets/185051/bda5ccc9-9c1b-4f38-8358-d4e4602b0763)

**Comment by kish5430** [comment]
HI Team,

I have deployed Attu pod with dev version. But still its not supporting and giving below error.

$ kubectl logs milvus-attu-5cc84674b7-zpjmm -n isds-milvus
exec /usr/local/bin/docker-entrypoint.sh: exec format error

Thanks

**Comment by shanghaikid** [comment]
new attu is released. 

![image](https://github.com/zilliztech/attu/assets/185051/624bf7e6-be34-46c7-bbc0-c94a16bfc53a)
