### ISSUE TITLE
reverse proxy by nginx error

### ISSUE THREAD

**Issue by v4if** [zilliztech/attu#315]
**Describe the bug:**
behind nginx with a sub path, how to set the resource root path with the sub path
such as: http://example.com/path/to/milvus

nginx config:
```
  location /path/to/milvus/ {
    proxy_pass http://11.132.42.228:30006;
    proxy_set_header Host $http_host;
  }
```

request the url：[http://example.com/path/to/milvus，response](http://example.com/path/to/milvus%EF%BC%8Cresponse) the error：
![image](https://github.com/zilliztech/attu/assets/16042235/c89d14d0-588e-4059-8d47-00555011d499)

**Attu version:**
zilliz/attu:v2.2.8

**Comment by shanghaikid** [comment]
Try this?
```
location /path/to/milvus/ {
    proxy_pass http://11.132.42.228:30006/;
    proxy_set_header Host $http_host;
  }
```

**Comment by v4if** [comment]
> Try this?
> 
> ```
> location /path/to/milvus/ {
>     proxy_pass http://11.132.42.228:30006/;
>     proxy_set_header Host $http_host;
>   }
> ```

Connect request url 404，request directly from the root path `https://example.com/api/v1/milvus/connect` without including subpath `/path/to/milvus/`, it should be `https://example.com/path/to/milvus/api/v1/milvus/connect`
![image](https://github.com/zilliztech/attu/assets/16042235/2205aac3-2b80-4b77-8361-7135766ee54c)

**Comment by shanghaikid** [comment]
> > Try this?
> > ```
> > location /path/to/milvus/ {
> >     proxy_pass http://11.132.42.228:30006/;
> >     proxy_set_header Host $http_host;
> >   }
> > ```
> 
> Connect request url 404，request directly from the root path `https://example.com/api/v1/milvus/connect` without including subpath `/path/to/milvus/`, it should be `https://example.com/path/to/milvus/api/v1/milvus/connect` ![image](https://user-images.githubusercontent.com/16042235/284803245-2205aac3-2b80-4b77-8361-7135766ee54c.png)

I'm not the expert of nginx. From the case, it looks like your should proxy `https://example.com/path/to/milvus/api/*` to `http://11.132.42.228:30006/api/*`; not sure how to write the rule, you can do some experiments.

**Comment by v4if** [comment]
This url `https://example.com/api/v1/milvus/connect` seems to be returned by attu's backend, like`https:://$root_url/api/v1/milvus/connect`, Is there any way to modify the root_url to `https://example.com/path/to/milvus` of attu?

Just like `run-grafana-behind-a-proxy`:
![image](https://github.com/zilliztech/attu/assets/16042235/63681f5a-d4ca-43f5-8faa-c003dadbea81)

https://grafana.com/tutorials/run-grafana-behind-a-proxy/

**Comment by shanghaikid** [comment]
I see. will fix it soon.

**Comment by carlwang99** [comment]
Did the problem fixed?
Have met the same problem of the url /api/xxx

**Comment by shanghaikid** [comment]
> Did the problem fixed? Have met the same problem of the url /api/xxx

For the release `v2.3.3`, you can setup `HOST_URL` as the docker env,   then you can set a correct root url.

**Comment by shanghaikid** [comment]
I don't have the env, but I can give you an example, you need to test it by yourself:)

```bash
location /path/to/milvus/ {
    proxy_pass http://11.132.42.228:30006/;
    proxy_set_header Host $http_host;
  }

```

```bash 
dock run -e HOST_URL= /path/to/milvus/  -p 30006:3000 zilliz/attu:v2.3.3
```

For this case, all the requests send from you browsers should be prefixed with `/path/to/milvus/` .  and it should go to the real address behind the `/path/to/milvus/`

**Comment by carlwang99** [comment]
突然404了
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /path/to/milvus/api/v1/milvus/connect</pre>
</body>
</html>
不知道发生了什么
服务器经过一次扩容，可是配置都没有改过。
2.3.3版本

**Comment by sky-cloud** [comment]
> > I don't have the env, but I can give you an example, you need to test it by yourself:)
> > ```shell
> > location /path/to/milvus/ {
> >     proxy_pass http://11.132.42.228:30006/;
> >     proxy_set_header Host $http_host;
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```shell
> > dock run -e HOST_URL= /path/to/milvus/  -p 30006:3000 zilliz/attu:v2.3.3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For this case, all the requests send from you browsers should be prefixed with `/path/to/milvus/` . and it should go to the real address behind the `/path/to/milvus/`
> 
> ok, it works dock run -e HOST_URL= /path/to/milvus/ -p 30006:3000 zilliz/attu:v2.3.3 location /example/vec/ { proxy_pass http://localhost:30006/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto $scheme; }
> 
> location /path/to/milvus/ { proxy_pass http://localhost:30006/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto $scheme; }

Thanks! I meet the same problem. Now I followed this configuration and I can login to see users, roles and metrics. But I cannot see the database! (see the figure below. There should be a database and a collection.)
![shot_20240410-174900](https://github.com/zilliztech/attu/assets/9923507/cb6c5c6c-ccae-4413-9095-6bc716d35fac)

Milvus is deployed at host 10.15.85.78, attu is deployed at host 10.15.86.23, nginx is deployed at local. The docker-compose for attu is as follows:
```yaml
version: '3.8'        
                      
services:             
  attu:               
    image: zilliz/attu:v2.3.9
    container_name: attu
    restart: always   
    hostname: attu       
    environment:         
      - MILVUS_URL=10.15.85.78:19530
      - HOST_URL=/attu                                                                                                                        
    ports:            
      - 5949:3000 
```

The configuration of nginx:
```       
location /attu/ {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://10.15.86.23:5949/;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
} 
```
Any help would be greatly appreciated.

**Comment by shanghaikid** [comment]
> > > I don't have the env, but I can give you an example, you need to test it by yourself:)
> > > ```shell
> > > location /path/to/milvus/ {
> > >     proxy_pass http://11.132.42.228:30006/;
> > >     proxy_set_header Host $http_host;
> > >   }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```shell
> > > dock run -e HOST_URL= /path/to/milvus/  -p 30006:3000 zilliz/attu:v2.3.3
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > For this case, all the requests send from you browsers should be prefixed with `/path/to/milvus/` . and it should go to the real address behind the `/path/to/milvus/`
> > 
> > 
> > ok, it works dock run -e HOST_URL= /path/to/milvus/ -p 30006:3000 zilliz/attu:v2.3.3 location /example/vec/ { proxy_pass http://localhost:30006/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto $scheme; }
> > location /path/to/milvus/ { proxy_pass http://localhost:30006/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto $scheme; }
> 
> Thanks! I meet the same problem. Now I followed this configuration and I can login to see users, roles and metrics. **But I cannot see the database!** (see the figure below. There should be a database and a collection.) ![shot_20240410-174900](https://private-user-images.githubusercontent.com/9923507/321186957-cb6c5c6c-ccae-4413-9095-6bc716d35fac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDQxMzEsIm5iZiI6MTcxMjc0MzgzMSwicGF0aCI6Ii85OTIzNTA3LzMyMTE4Njk1Ny1jYjZjNWM2Yy1jY2FlLTQ0MTMtOTA5NS02YmM3MTZkMzVmYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTBUMTAxMDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2VjN2M2ODIxMDU3OTYyNTFjODdjODljMzIzZjBkNjNjNmExNDNkMDRlYjJmZWE3NmRhODUwZjMyOGEwODNjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YcZqQSQRkBw1osE16fiMg1CzUFOEOp0hW6_SthGSJzc)
> 
> Milvus is deployed at host 10.15.85.78, attu is deployed at host 10.15.86.23, nginx is deployed at local. The docker-compose for attu is as follows:
> 
> ```yaml
> version: '3.8'        
>                       
> services:             
>   attu:               
>     image: zilliz/attu:v2.3.9
>     container_name: attu
>     restart: always   
>     hostname: attu       
>     environment:         
>       - MILVUS_URL=10.15.85.78:19530
>       - HOST_URL=/attu                                                                                                                        
>     ports:            
>       - 5949:3000 
> ```
> 
> The configuration of nginx:
> 
> ```
> location /attu/ {
>             proxy_set_header Host $http_host;
>             proxy_set_header X-Real-IP $remote_addr;
>             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>             proxy_set_header X-Forwarded-Proto $scheme;
>             proxy_pass http://10.15.86.23:5949/;
>             proxy_set_header Upgrade $http_upgrade;
>             proxy_set_header Connection "Upgrade";
> } 
> ```
> 
> Any help would be greatly appreciated.

looks like the websocket is not forwarded.  can you enable the `big request rows` on chrome inspector? 

![image](https://github.com/zilliztech/attu/assets/185051/818432de-4d4d-4da8-8129-971695b72bc3)

**Comment by sky-cloud** [comment]
> > > > I don't have the env, but I can give you an example, you need to test it by yourself:)
> > > > ```shell
> > > > location /path/to/milvus/ {
> > > >     proxy_pass http://11.132.42.228:30006/;
> > > >     proxy_set_header Host $http_host;
> > > >   }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ```shell
> > > > dock run -e HOST_URL= /path/to/milvus/  -p 30006:3000 zilliz/attu:v2.3.3
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > For this case, all the requests send from you browsers should be prefixed with `/path/to/milvus/` . and it should go to the real address behind the `/path/to/milvus/`
> > > 
> > > 
> > > ok, it works dock run -e HOST_URL= /path/to/milvus/ -p 30006:3000 zilliz/attu:v2.3.3 location /example/vec/ { proxy_pass http://localhost:30006/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto $scheme; }
> > > location /path/to/milvus/ { proxy_pass http://localhost:30006/; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto $scheme; }
> > 
> > 
> > Thanks! I meet the same problem. Now I followed this configuration and I can login to see users, roles and metrics. **But I cannot see the database!** (see the figure below. There should be a database and a collection.) ![shot_20240410-174900](https://private-user-images.githubusercontent.com/9923507/321186957-cb6c5c6c-ccae-4413-9095-6bc716d35fac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDQxMzEsIm5iZiI6MTcxMjc0MzgzMSwicGF0aCI6Ii85OTIzNTA3LzMyMTE4Njk1Ny1jYjZjNWM2Yy1jY2FlLTQ0MTMtOTA5NS02YmM3MTZkMzVmYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTBUMTAxMDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2VjN2M2ODIxMDU3OTYyNTFjODdjODljMzIzZjBkNjNjNmExNDNkMDRlYjJmZWE3NmRhODUwZjMyOGEwODNjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YcZqQSQRkBw1osE16fiMg1CzUFOEOp0hW6_SthGSJzc)
> > Milvus is deployed at host 10.15.85.78, attu is deployed at host 10.15.86.23, nginx is deployed at local. The docker-compose for attu is as follows:
> > ```yaml
> > version: '3.8'        
> >                       
> > services:             
> >   attu:               
> >     image: zilliz/attu:v2.3.9
> >     container_name: attu
> >     restart: always   
> >     hostname: attu       
> >     environment:         
> >       - MILVUS_URL=10.15.85.78:19530
> >       - HOST_URL=/attu                                                                                                                        
> >     ports:            
> >       - 5949:3000 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The configuration of nginx:
> > ```
> > location /attu/ {
> >             proxy_set_header Host $http_host;
> >             proxy_set_header X-Real-IP $remote_addr;
> >             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> >             proxy_set_header X-Forwarded-Proto $scheme;
> >             proxy_pass http://10.15.86.23:5949/;
> >             proxy_set_header Upgrade $http_upgrade;
> >             proxy_set_header Connection "Upgrade";
> > } 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any help would be greatly appreciated.
> 
> looks like the websocket is not forwarded. can you enable the `big request rows` on chrome inspector?
> 
> ![image](https://private-user-images.githubusercontent.com/185051/321202681-818432de-4d4d-4da8-8129-971695b72bc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3OTczOTIsIm5iZiI6MTcxMjc5NzA5MiwicGF0aCI6Ii8xODUwNTEvMzIxMjAyNjgxLTgxODQzMmRlLTRkNGQtNGRhOC04MTI5LTk3MTY5NWI3MmJjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQwMDU4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODVmOTA5YjM4NWVlN2NhZmRhY2QzZWIwYmViMmVkMzY3Y2VlMGNjMmI5MjQ0ZmNiZjE4YWE4Y2QxNjhhYjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bez5qpAm_sw2ExsooqAD-Zo5CdwxtqadoqUnI-bISSM)

Thank you. I enable the `big request rows` on chrome inspector. Please see the screenshots blew.
![shot_20240411-101732](https://github.com/zilliztech/attu/assets/9923507/0dc688e1-b1f6-468d-8216-eaf2013e0204)

And also the header info:
![shot_20240411-101820](https://github.com/zilliztech/attu/assets/9923507/c05b480c-1557-4c85-8035-9b518c6cd842)

**Comment by shanghaikid** [comment]
@sky-cloud  can you check this, if this is empty, I think the `HOST_URL` is not set correctly.
![image](https://github.com/zilliztech/attu/assets/185051/f5985828-8e74-41a4-8b2a-c2daf8e0c68f)

**Comment by sky-cloud** [comment]
> @sky-cloud can you check this, if this is empty, I think the `HOST_URL` is not set correctly. ![image](https://private-user-images.githubusercontent.com/185051/321471838-f5985828-8e74-41a4-8b2a-c2daf8e0c68f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MTM1NTMsIm5iZiI6MTcxMjgxMzI1MywicGF0aCI6Ii8xODUwNTEvMzIxNDcxODM4LWY1OTg1ODI4LThlNzQtNDFhNC04YjJhLWMyZGFmOGUwYzY4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQwNTI3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGZkMzI1MDk2NGY1MzAyYjZlOTUzYWNlOWY3M2VjYmRkZDA3YTNkMGI5NzI3NGMwMzNlM2Y5NzAxMWFhMDNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.okX-lqQ7CUIHR9l4J2JJuSlEfXYr5fJSU6VpRhVsoSY)

@shanghaikid Thanks for you reply. The `_env_.HOST_URL` is as follows:
![shot_20240411-133036](https://github.com/zilliztech/attu/assets/9923507/76530608-b8e5-4b15-892a-cf66ed3bcc40)

**Comment by sky-cloud** [comment]
@shanghaikid Some additional notes may be helpful. 
1. Although I cannot see the database or collection, I can create new collection in default database. see the screenshots follow:
![shot_20240411-134448](https://github.com/zilliztech/attu/assets/9923507/89e7e938-666a-4d8d-b52b-80a73eb7a684)

I create a collection named `new_col` and see the notification of success:
![shot_20240411-134507](https://github.com/zilliztech/attu/assets/9923507/3a8ba2c2-5269-4941-a419-0a5890f9bbc8)

2. If I use `location / {...}` other than `location /somepath {...}` in nginx, then everything is OK. Under this condition the env variable `HOST_URL` is also not necessary for running zilliz/attu. Now I can see the collection `new_col` in the default database:
![shot_20240411-134642](https://github.com/zilliztech/attu/assets/9923507/94f90650-c2aa-4d05-9244-bdda40361ac7)

**Comment by shanghaikid** [comment]
```nginx
server {
  listen 8080;
  server_name localhost;

  location /attu/ {
    proxy_pass http://localhost:3000/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    rewrite ^/attu/(.*)$ /$1 break;
  }
}
```
This conf works for me.

![image](https://github.com/zilliztech/attu/assets/185051/55a8c6dc-dbde-414b-b7b6-1661330477ed)
