### ISSUE TITLE
attu 无法修改root用户密码， 其他用户密码则可以

### ISSUE THREAD

**Issue by jkl0898** [zilliztech/attu#317]
**Describe the bug:**

attu 开启用户认证后，更新root 密码报错。
报500 错误， 显示无法更新默认的root 密码。

ps: 新建一个用户， 并修改密码成功。

**Steps to reproduce:**
1. 以root用户登录attu 控制台
2. 选中root 用户并执行Update password
3. 页面报500 错误。无法修改

**Attu version:**
v2.3.2 、v2.2.8

**Comment by shanghaikid** [comment]
I can't reproduce this on my laptop. can you paste the error detail?  what is your milvus version?

**Comment by jkl0898** [comment]
> I can't reproduce this on my laptop. can you paste the error detail? what is your milvus version?

<img width="1502" alt="image" src="https://github.com/zilliztech/attu/assets/14175165/24d2125c-aa77-4198-979b-f455de76c2f6">

the old password is missing now， original is Milvus， can't modify again.  
version is  v2.3.2 、v2.2.8

**Comment by jkl0898** [comment]
<img width="1131" alt="image" src="https://github.com/zilliztech/attu/assets/14175165/e2a41c4f-e4dd-425c-9c6e-3f6db48a6d20">
the original password “Milvus” is not correct now,  when I modified first, it doesn't success. 
the version is v2.3.2

**Comment by shanghaikid** [comment]
That's weird. I can update the password, I tested in a fresh installed milvus v2.3.3.   did you type the correct `current password`. 
![image](https://github.com/zilliztech/attu/assets/185051/f7ba8e2e-b2c1-425c-9565-315efc093a14)

**Comment by jkl0898** [comment]
> That's weird. I can update the password, I tested in a fresh installed milvus v2.3.3. did you type the correct `current password`. ![image](https://user-images.githubusercontent.com/185051/284550783-f7ba8e2e-b2c1-425c-9565-315efc093a14.png)

due to modified unsuccessfuly in the first time, i don't know the password now. my version is v2.3.2.

**Comment by shanghaikid** [comment]
> > That's weird. I can update the password, I tested in a fresh installed milvus v2.3.3. did you type the correct `current password`. ![image](https://user-images.githubusercontent.com/185051/284550783-f7ba8e2e-b2c1-425c-9565-315efc093a14.png)
> 
> due to modified unsuccessfuly in the first time, i don't know the password now. my version is v2.3.2.

Please refer to https://milvus.io/docs/authenticate.md#Reset-password ,

1. disable `authorizationEnabled`
2. add `root` in the `superuser` section, then milvus will not check old password
3. using attu or api to modify the password for `root`
4. enable `authorizationEnabled`
5. done.
