### ISSUE TITLE
Privileges assigned to Roles goes missing on editing the role from Attu

### ISSUE THREAD

**Issue by Rachit-Chaudhary11** [zilliztech/attu#322]
**Privileges assigned to roles on edit are removing the privileges**

**Steps to reproduce:**
1. Create a role and assign some privileges, it can be any privilege and save the role.
2. Edit the role by adding some new privileges to it, keeping the ones from Step # 1 also selected as it and save the role
3. Role will only be having the privileges assigned from Step # 2 and not from Step # 1 even though they were selected too at the time of roles edition
4. Same can also we tested by editing a role without any update and saving it, this will remove all the privileges even though during save they were selected

**Attu version:**
Version: 2.8.8

**Comment by shanghaikid** [comment]
can you show me what privileges are included in the role?

**Comment by Rachit-Chaudhary11** [comment]
@shanghaikid I have updated the issue description with the steps. Kindly follow them to reproduce the issue
Also, it is a generic issue and nothing to do with any particular privilege.

**Comment by shanghaikid** [comment]
> @shanghaikid I have updated the issue description with the steps. Kindly follow them to reproduce the issue Also, it is a generic issue and nothing to do with any particular privilege.

OK, I will check it later.

**Comment by Rachit-Chaudhary11** [comment]
@shanghaikid I see this issue has been resolved in latest Attu Version. 
I am going ahead and closing it. Thanks.

**Comment by shanghaikid** [comment]
ok, still the UI doesn't respect the RBAC settings, it takes time to resolve it. anyway, I am hoping you like attu.
