### ISSUE TITLE
系统语言为中文时无法删除collection

### ISSUE THREAD

**Issue by NaMoCv** [zilliztech/attu#336]
**Describe the bug:**
系统语言为中文时无法删除collection，提示删除成功，但是并没有删除。

**Attu version:**
2.3.4
2.3.3无法连接2.3.3的milvus

**Comment by e345** [comment]
最好让用户自主选择切换语言，遇到同样语言问题。

**Comment by e345** [comment]
建议类似这种“drop: '放弃'”,等确认词不要翻译，否则填写中文确认会有问题
