### ISSUE TITLE
Attu-SSL Enablement issue

### ISSUE THREAD

**Issue by sahusasank** [zilliztech/attu#337]
Hello ,

I have deployed Milvus 2.2.8 through Milvus helm chart ( milvus-4.0.20) on my kubernetes Cluster.
Our requirement is to enable SSL/TLS on Milvus which i have done and able to communicate through Python client.

But I am not able to enable SSL on Attu, when i am enabling SSL then connection is not establishing. Hence we are facing a huge challenges to manage and maintain Milvus vector DB.

Please help me to fix this issue?

**Comment by shanghaikid** [comment]
fixed.
