### ISSUE TITLE
Index name under the segment information displayed in attu v2.3.5 is incorrect.

### ISSUE THREAD

**Issue by wutachiang** [zilliztech/attu#350]
**Describe the bug:**
There are scalar indexes and vector indexes in the default schema. The index names displayed in the segment information confuse the scalar and vector index names.

**Steps to reproduce:**
1.Create a new collection with scalar and vector indexes 
![image](https://github.com/zilliztech/attu/assets/13926708/5cae9896-37f5-4b91-936c-71c10c5e5081)
2. Observe the details of segment information
![image](https://github.com/zilliztech/attu/assets/13926708/8375d427-a0ed-4586-bfdf-4cc7697726da)

**Attu version:**
2.3.5

**Comment by wutachiang** [comment]
milvus version: 2.3.4

**Comment by shanghaikid** [comment]
I will hide this info for now.
