### ISSUE TITLE
Support GetFlushState and GetFlushAllState for rbac dialog

### ISSUE THREAD

**Issue by nameczz** [zilliztech/attu#352]
**Describe the feature:**
Support GetFlushState and GetFlushAllState for rbac dialog

**Describe a specific use case for the feature:**

![img_v3_026t_21fb3c91-3a4a-4e5a-8bca-c24aeef717ag](https://github.com/zilliztech/attu/assets/20559208/7871c87d-ba25-4adf-a720-eb8ec8b3d517)

**Comment by nameczz** [comment]
![img_v3_026t_014a9240-9e96-475c-bd17-c34ac47e4c5g](https://github.com/zilliztech/attu/assets/20559208/17f78080-9ef3-4d6c-99ee-f7e6ef95abab)
Need to support two more apis.

**Comment by shanghaikid** [comment]
fixed.
