### ISSUE TITLE
run container failed

### ISSUE THREAD

**Issue by lironghai** [zilliztech/attu#355]
**Describe the bug:**
milvus Started
attu logs:

node[1]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb95b60 node::Abort() [node]
 2: 0xb95bde  [node]
 3: 0xc0447e  [node]
 4: 0xc04561 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xb50e03 node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [node]
 6: 0xb5145b node::Start(int, char**) [node]
 7: 0x7f84e5c341ca  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f84e5c34285 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xacfdce _start [node]

**Steps to reproduce:**
1.
2.
3.

**Attu version:**
2.3.5

**Attu version:**

**Comment by lironghai** [comment]
> what's your docker version ?

docker version  20.10.9

**Comment by shanghaikid** [comment]
> > what's your docker version ?
> 
> docker version 20.10.9

Maybe you should upgrade it. 
 https://github.com/nodejs/node/issues/43064#issuecomment-1811525001

**Comment by lironghai** [comment]
> > > what's your docker version ?
> > 
> > 
> > docker version 20.10.9
> 
> Maybe you should upgrade it. [nodejs/node#43064 (comment)](https://github.com/nodejs/node/issues/43064#issuecomment-1811525001)

session-record-switch: true
