### ISSUE TITLE
Add Support for Visualizing Dynamic Schema Fields in Attu

### ISSUE THREAD

**Issue by HantaoCai** [zilliztech/attu#379]
**Describe the feature:**
The proposed feature would involve enhancing the Attu interface to support the visualization of dynamic schema fields in Milvus collections. Currently, collections in Milvus can evolve with dynamic schemas, but these changes are not reflected in the Attu UI. The feature would allow Attu to display all fields of a collection, including those that are dynamically added or altered after the initial schema is set up.

**Describe a specific use case for the feature:**
In the current scenario, when dynamic fields are added to a Milvus collection, the only way to view and interact with these fields is through the Milvus SDK. Developers and data scientists must write and execute custom code to retrieve and view this information, which can be cumbersome and time-consuming. For example, when a new set of features is added to a collection as part of a data update process, users have to rely on the SDK to access the updated schema and the new data points.

This process lacks the convenience and immediacy of a visual tool. With the addition of this feature to Attu, users would be able to immediately see the updated schema and corresponding data directly within the Attu interface, without the need for additional coding. This would streamline workflows for users who need to manage and explore evolving datasets, making it easier to verify and understand the structure of their data in real-time.

**Comment by shanghaikid** [comment]
which version of attu are you using? 

![image](https://github.com/zilliztech/attu/assets/185051/a9a0a6c0-e5fd-4dbf-ac25-4ba996af8d66)

![image](https://github.com/zilliztech/attu/assets/185051/ae6c9dc0-418e-4a31-8820-30d2a6ac6612)

**Comment by HantaoCai** [comment]
I apologize for still using version 2.3.1, I didn't notice the update.
