### ISSUE TITLE
some small problems

### ISSUE THREAD

**Issue by JackLCL** [zilliztech/attu#381]
**Describe the bug:**
![image](https://github.com/zilliztech/attu/assets/53512883/bd61ebb2-4d84-4025-94aa-b234b96f6d6c)

1. scan this QR  code, I get the following error:
![image](https://github.com/zilliztech/attu/assets/53512883/39cdc245-184b-4867-828e-560d95fd2d2c)

2. Currently, more people use Discord for community communication. A Discord link should be added.

**Steps to reproduce:**
1.
3.
4.

**Attu version:**

**Attu version:**

**Comment by shanghaikid** [comment]
will fix it in the next release
