### ISSUE TITLE
Delete chunks in Attu UI is failing

### ISSUE THREAD

**Issue by benauriemma** [zilliztech/attu#390]
**Describe the bug:**

I'm trying to delete chunks from Milvus in the Attu UI, but it's failing with the red error toast shown.
<img width="425" alt="Screenshot 2024-01-30 at 1 50 58 PM" src="https://github.com/zilliztech/attu/assets/26725999/384f544b-3a26-4128-95a2-1fdd997c75ef">

**Steps to reproduce:**
1. Open Data Query page
2. Filter to the chunks I care about
3. Check the box next to one chunk
4. Click the trash icon and type "drop" to confirm
5. I get the red error toast shown in the screenshot
6. I've tried this with multiple chunks at the same time and get the same error

**Attu version:** 2.2.5

**Comment by shanghaikid** [comment]
looks like a milvus issue. 
what's your milvus verison?
