### ISSUE TITLE
Any tools for synchronization from mysql to milvus?

### ISSUE THREAD

**Issue by carlwang99** [zilliztech/attu#391]
**Describe the feature:**
log-based synchronization

**Describe a specific use case for the feature:**
now i use python script to migrate data to milvus.
when i edit the data in mysql, how to synchronize it to milvus?

**Comment by shanghaikid** [comment]
As far as I know, no. 

But you can ask it in the milvus repo. 

https://github.com/milvus-io/milvus/issues。
