### ISSUE TITLE
Wrong sort order by Approx Count field in Collection tab

### ISSUE THREAD

**Issue by SthPhoenix** [zilliztech/attu#392]
**Describe the bug:**
Sorting by `Approx Count` is executed in alphabetical order

**Steps to reproduce:**
1. Open GUI
2. Go to `Collection` tab
3. Click on `Approx count` to change sort order

**Attu version:**
at least 2.2.3 - 2.3.7

**Comment by shanghaikid** [comment]
I am redesigning the collections page. maybe there is no `approx count` sort of things  on this page, because if a user has 10k collections, we need to fetch the `approx count` 10k times, which makes the page unusable.
