### ISSUE TITLE
The Collections loading slow

### ISSUE THREAD

**Issue by xTerry** [zilliztech/attu#393]
**Describe the bug:**
Attu loading collecitons slow

**Steps to reproduce:**
1. open attu url 
2. connected milvus
3. home：cost 70s
4. collection：cost 63s
5. vectors search：cost  130s

**Attu version:**
V2.3.6 

**Milvus version:**
V2.2.16

**Milvus env***
by k8s DISTRIBUTED
data count: 1.3 billion+
collection num: 70

**Comment by shanghaikid** [comment]
known issue. #384
