### ISSUE TITLE
Records with Primary key < 1 for INT64 field are not shown in UI

### ISSUE THREAD

**Issue by rossbg** [zilliztech/attu#396]
**Describe the bug:**
Data with Primary key < 1 for INT64 field are not shown in UI

**Steps to reproduce:**
1. Insert records with primary key < 1
2. Open collection 
3. Observe results. Not showing records with PK < 1. There are 2 such records in this example, and they are counted in the total rows at the bottom (1 - 6 of 6 result)
<img width="537" alt="79f52d229a1361598d9a7b114f44b2d7" src="https://github.com/zilliztech/attu/assets/1425609/55deb920-4024-452e-889c-8346d21a64f2">

4. Note: All records are correctly stored and returned if they are queried with pymilvus.

**Attu version:**
2.3.7

**Comment by shanghaikid** [comment]
looks like a milvus problem, I tested with node sdk, I inserted the float value on the int64 field, but failed to query, the count api is working as well. 

Can you show me the pymilvus code?

**Comment by shanghaikid** [comment]
I see, so your id is negative number. I will fix this.
