### ISSUE TITLE
Database list is restricted to unauthorized users.

### ISSUE THREAD

**Issue by kish5430** [zilliztech/attu#398]
**Describe the feature:**
list and show the specific databases to user which are having access to that user

**Describe a specific use case for the feature:**
1. Create two databases, 'db_1' and 'db_2', with the root user.
2. Select database 'db_1' from the database list and create a role called 'role_1'. Add all collection level privileges to that role and add a few global privileges (Create Collection, Drop Collection, Describe Collection, Show Collections, List Databases).
3. Create a user named 'user_1' and assign the role 'role_1'.
4. Select the database 'db_2' from the database list and create a role called 'role_2'. Add all collection level privileges to that role and add a few global privileges (Create Collection, Drop Collection, Describe Collection, Show Collections, List Databases).
5.  Create a user named 'user_2' and assign the role 'role_2'.
Log out from the root user and log in using the details below.
            username: user_1
            password: xxxxxxx
            database: db_1
6. User 'user_1' is able to log in and database 'db_1' is being selected in the drop-down list by default. Here, 'user_1' is able to see all the remaining databases.
7. User 1 may not be able to access the collections, but he can still view all the databases.
8. The goal is for 'user_1' to only see the database, regardless of their privileges.

Thanks

**Comment by kish5430** [comment]
Can you plz share any ETA to release this feature

**Comment by kish5430** [comment]
@shanghaikid 
Can you plz share any ETA to release this feature

**Comment by shanghaikid** [comment]
I hope it will be released in this month.

**Comment by shanghaikid** [comment]
https://github.com/zilliztech/attu/pull/429

**Comment by shanghaikid** [comment]
please try v2.3.9.

**Comment by kish5430** [comment]
HI @shanghaikid 
I have upgraded to Attu 2.3.9 version but it is not working as expected. Plz check below test scenario.

Step 1; Create a database(db_name=test_db)
Step 2: create a role and provided below privileges to a role(test_role)

		role.grant("Global", "*", "CreateCollection", db_name=db_name)
        role.grant("Global",  "*", "DropCollection", db_name=db_name)
        role.grant("Global",  "*", "DescribeCollection", db_name=db_name)
        role.grant("Global",  "*", "ShowCollections", db_name=db_name)
        role.grant("Global",  "*", "SelectOwnership", db_name=db_name)
        role.grant("Global",  "*", "ManageOwnership", db_name=db_name)
        role.grant("Collection", "*", "*", db_name=db_name)

Step 3: Create a user(test_user) and assigned to a role(test_role)
Step 4: Now i tried to login with 'test_user' details, getting error message "Error: You don't have permission to access the database: test_db."

Please check and fix the issue.

Thanks

**Comment by shanghaikid** [comment]
> HI @shanghaikid I have upgraded to Attu 2.3.9 version but it is not working as expected. Plz check below test scenario.
> 
> Step 1; Create a database(db_name=test_db) Step 2: create a role and provided below privileges to a role(test_role)
> 
> ```
> 	role.grant("Global", "*", "CreateCollection", db_name=db_name)
>     role.grant("Global",  "*", "DropCollection", db_name=db_name)
>     role.grant("Global",  "*", "DescribeCollection", db_name=db_name)
>     role.grant("Global",  "*", "ShowCollections", db_name=db_name)
>     role.grant("Global",  "*", "SelectOwnership", db_name=db_name)
>     role.grant("Global",  "*", "ManageOwnership", db_name=db_name)
>     role.grant("Collection", "*", "*", db_name=db_name)
> ```
> 
> Step 3: Create a user(test_user) and assigned to a role(test_role) Step 4: Now i tried to login with 'test_user' details, getting error message "Error: You don't have permission to access the database: test_db."
> 
> Please check and fix the issue.
> 
> Thanks

Actually milvus doesn't support this db level control, it is not a ABAC system, it is a RBAC system.
Attu does a little thing for this, but you need to grant the user ListDatabases on the specific db.

**Comment by kish5430** [comment]
@shanghaikid After granting the user with the ListDatabases privilege, I am able to see only the specific database.
But in the command line, I can see all databases irrespective of privilege after providing the 'listdatabases' privilege. I hope if you can show the database list in Attu without providing the ListDatabases privilege, it will fix the issue.

**Comment by shanghaikid** [comment]
> @shanghaikid After granting the user with the ListDatabases privilege, I am able to see only the specific database. But in the command line, I can see all databases irrespective of privilege after providing the 'listdatabases' privilege. I hope if you can show the database list in Attu without providing the ListDatabases privilege, it will fix the issue.

That's out my scope, you should ask milvus team to support this.
