### ISSUE TITLE
standard_init_linux.go:224: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by AnitaSherry** [zilliztech/attu#415]
**Describe the bug:**
standard_init_linux.go:224: exec user process caused "exec format error"

**Steps to reproduce:**
1.docker run -p 8000:3000 -e MILVUS_URL={milvus server IP}:19530 zilliz/attu:v2.3.8

**Comment by shanghaikid** [comment]
which system are you using? what is your docker version?

**Comment by AnitaSherry** [comment]
Linux localhost.localdomain 5.10.0-60.18.0.50.oe2203.aarch64 #1 SMP Wed Mar 30 02:43:08 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
Docker version 18.09.0, build 172f8da

**Comment by shanghaikid** [comment]
We do not provide arm64 based docker image yet. I think we will provide a test ARM image in this week.

**Comment by shanghaikid** [comment]
We have released arm image on the dev channel, you can have a try.


![image](https://github.com/zilliztech/attu/assets/185051/bf900716-63a0-48be-96d7-866bba80075b)
