### ISSUE TITLE
Failed to delete selected data in Data Query

### ISSUE THREAD

**Issue by Renekton** [zilliztech/attu#43]
**Describe the bug:**

Users can not delete selected data in Data Query

**Steps to reproduce:**
1. select some item in Data Query
![image](https://user-images.githubusercontent.com/7531084/157391136-0039cf25-6bf6-4059-98c3-cdf2f0057157.png)

2. click the "Delete button", and delete the selected data
![image](https://user-images.githubusercontent.com/7531084/157391285-adabe54f-388d-4bda-8633-8f50663f5ae1.png)

3. attu shows that the deletion was successful
4. refresh the attu，requery the data，In fact, the deletion was not successful.
![image](https://user-images.githubusercontent.com/7531084/157415904-96ac89d5-b9cd-497e-aec2-c887790abcd2.png)

6. Re-delete the selected data, The prompt error is as follows：
![image](https://user-images.githubusercontent.com/7531084/157416153-b8b8cfdd-0f0d-45e1-880d-97a3c249a438.png)

**Attu version:**
 v1.22.10

**Attu version:**

**Comment by nameczz** [comment]
Already fixed, you can try with attu v2.0.5.
Thanks for the issue, any more questions are welcome!
