### ISSUE TITLE
Change default port via Environment Variable

### ISSUE THREAD

**Issue by TheDropZone** [zilliztech/attu#431]
Currently, in the app.ts express setup
```typescript
const PORT = 3000;
//.......
// start server
server.listen(PORT, () => {
  const ips = getIp();
  ips.forEach(ip => {
    console.info(chalk.cyanBright(`Attu server started: http://${ip}:${PORT}`));
  });
});
```
The server port is hard coded to "3000". Typically, given this is deployed via docker in many situations, the port is allowed to be overridden via an environment variable so that your environment can choose what port to host on.
Yes, you can just use docker bridge networking to map a port to whatever port you would like, but depending on your requirements, you may be using docker-host based networking, which does not provide that feature. Additionally, when running this locally, it's always nice to have control over what port you are running on.

**Proposed Change**
Instead of 
_/server/src/app.ts_
```typescript
const PORT = 3000;
server.listen(PORT, () => {
```

Update to
```typescript
// use port 3000 unless there exists a preconfigured port
const PORT = process.env.PORT || 3000;
server.listen(PORT, () => {
```

----

I'm glad to put up an MR for this as well, just wanted to see if there was a reason to not do this. Thanks!

**Comment by shanghaikid** [comment]
Hi, there. there is no special reason for using 3000. yes pr is welcomed. 😀

**Comment by TheDropZone** [comment]
Thanks @shanghaikid.
I made the updates and have a pull request up: https://github.com/zilliztech/attu/pull/434

**Comment by TheDropZone** [comment]
Thanks @shanghaikid.
I made the updates and have a pull request up: https://github.com/zilliztech/attu/pull/434
