### ISSUE TITLE
sort bug for number: 5.456623109086067e-13 in milvus 2.3.1

### ISSUE THREAD

**Issue by weiZhenkun** [zilliztech/attu#432]
**Describe the bug:**

![image](https://github.com/zilliztech/attu/assets/27683687/9eb1dbd0-d56b-4370-8f67-3dde9e3b4d95)

**Comment by shanghaikid** [comment]
attu won't change data returned from milvus. 
If you think the score is not reasonable, please file an issue on https://github.com/milvus-io/milvus
