### ISSUE TITLE
Milvus Version Display Error When Upgrading Milvus Using milvus-operator

### ISSUE THREAD

**Issue by ian-lss** [zilliztech/attu#437]
**Describe the bug:**
When upgrading Milvus version using a Helm chart, the Milvus Version updates correctly in Attu. 
However, when using the milvus-operator for the upgrade, the Milvus Version does not always update and remains displayed as the previous version. Interestingly, in 8 tests, only once did the version update correctly. 
Despite this, checks in ArgoCD for each component show that the upgrade has completed successfully. 
Furthermore, when checking the version on clusters where Attu did not reflect the updated version, using utility.getversion() from pymilvus correctly outputs the upgraded version. 
Tests were conducted for upgrades from 2.3.8 to 2.3.10 and from 2.3.8 to 2.3.11.

**Steps to reproduce:**
1.Upgrade using milvus-operator.
2.The upgrade mode is set with rollingUpgradeEnable true.
3.Check the Milvus Version in Attu.
4.Verify using pymilvus with print(utility.getversion()).

**Attu version:**
2.3.8

**Milvus version:**
2.3.8,2.3.10,2.3.11

**Comment by shanghaikid** [comment]
@haorenfsa do you have any idea of this?  I don't think this issue is related to attu. 
you may open a ticket on https://github.com/zilliztech/milvus-operator

**Comment by ian-lss** [comment]
hi, @shanghaikid 


Do you have any reason to think so? 
Is it because Attu also exposes it by calling the REST API?
Initially, I also thought it was an issue with the milvus-operator and had already created a ticket there. 
However, upon analyzing the milvus-operator code, it seems that the milvus-operator does not directly update the version information but only changes the image and deploys it. 
Crucially, since the version information is correctly displayed in pymilvus, I am concluding that the upgrade was successful, and hence, I believe it to be an issue with Attu.

**Comment by shanghaikid** [comment]
attu server call milvus with milvus-node-sdk, not the restful api, and if you can get the correct version after upgrading with Helm chart, that should be a problem in attu.

**Comment by shanghaikid** [comment]
And there is no cache layer for the getVersion api, no matter in attu or in node sdk. so I don't think it is a problem of attu.  

@haorenfsa please help  : )

**Comment by shanghaikid** [comment]
@LoveEachDay do you have any idea?

**Comment by ian-lss** [comment]
I also confirmed that there is no cache in attu after reviewing its content.
Then, considering the different results between node sdk and pymilvus,
could this be an issue with Milvus?

**Comment by shanghaikid** [comment]
> I also confirmed that there is no cache in attu after reviewing its content. Then, considering the different results between node sdk and pymilvus, could this be an issue with Milvus?

@yanliang567 have you seen this kind of issue?

**Comment by shanghaikid** [comment]
is it correct after refreshing the page?

**Comment by haorenfsa** [comment]
Reproduced:

topology graph shows v2.3.11 already:
![img_v3_028v_5f2947af-be6e-407d-8e2a-5c1051c9f5eg](https://github.com/zilliztech/attu/assets/15938850/c236e6b2-ef30-4383-9199-5a4de9663f64)

main page still show system version is v2.3.10
![img_v3_028v_a590d97f-467d-41b1-b49e-7c7e1d1f9c0g](https://github.com/zilliztech/attu/assets/15938850/e4265911-c22a-4ab3-91e9-d7feef0eab63)


But in my case, if you refresh your page through ctrl + R , the version is corrected.


Another note is that the topology shows the version of each component. The middle big milvus circle shows the version of `rootcoord`. while the system version is from the `proxy`.

The rolling upgrade is conducted by order: indexnode -> coords -> querynode -> datanode -> proxy.

So when you see the coords are already in new version, the proxy might still not.

**Comment by ian-lss** [comment]
hi, @haorenfsa 

It's even stranger when viewed from the system view.
The rootcoord appears as 2.3.10.
<img width="1914" alt="스크린샷 2024-03-14 22 36 08" src="https://github.com/zilliztech/attu/assets/38341885/43e9b703-1c7f-4b95-b40b-0341bc1d5b17">

It is said that the version is checked from the proxy, but according to ArgoCD,
both proxies are 2.3.11, and of course, pymilvus's getVersion also shows 2.3.11.
![스크린샷 2024-03-14 22 34 09](https://github.com/zilliztech/attu/assets/38341885/18405a56-3a4e-477b-9b00-72a8275519f1)

Furthermore,
I was aware that the rolling upgrade order is indexnode -> coords -> querynode -> datanode -> proxy. But upon further inspection in the system view,
querycoord and datacoord are 2.3.10,
<img width="1898" alt="스크린샷 2024-03-14 22 59 50" src="https://github.com/zilliztech/attu/assets/38341885/81ff8cd9-4b27-4a63-96ea-62ca837858af">
<img width="1917" alt="스크린샷 2024-03-14 23 00 01" src="https://github.com/zilliztech/attu/assets/38341885/33150c6a-9e5b-4de3-8fbb-55f04338a731">

while querynode and datanode are 2.3.11.
<img width="1838" alt="스크린샷 2024-03-14 22 35 46" src="https://github.com/zilliztech/attu/assets/38341885/e04b2d73-cb9f-4c95-a0f4-0849f6b8a5c3">
<img width="1842" alt="스크린샷 2024-03-14 22 50 57" src="https://github.com/zilliztech/attu/assets/38341885/5ef1f6bb-c442-4fd5-9def-3707d435acf8">

I am using mixcoord, and as expected, it is also 2.3.11 according to ArgoCD.
![스크린샷 2024-03-14 22 33 46](https://github.com/zilliztech/attu/assets/38341885/cfe1a2f7-2f89-4eff-bf9d-0086a52424f7)

If the mixcoord's upgrade was not successful, shouldn't the data/query nodes not have been upgraded?
Therefore, since querynode and datanode are 2.3.11, could it be that the version perception on the coords side is incorrect, causing the system info milvus.version to be wrong?

**Comment by haorenfsa** [comment]
> Therefore, since querynode and datanode are 2.3.11, could it be that the version perception on the coords side is incorrect, causing the system info milvus.version to be wrong?

@ian-lss  It's possible. did you also check the image of mixcoord pod? is it already 2.3.11?

**Comment by haorenfsa** [comment]
@ian-lss could you also provide your `Milvus` CR manifest both before & after your upgrade? This would help us to reproduce it.

**Comment by ian-lss** [comment]
@haorenfsa 

The last attached image shows the mixcoord image version confirmed in ArgoCD.
Is this what you're referring to?

I attached it with the requested CR manifest.
```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: ai
spec:
  mode: cluster
  components:
    serviceAccountName: ai-milvus
    enableRollingUpdate: true
    imageUpdateMode: rollingUpgrade # Default value, can be omitted
    image: milvusdb/milvus:v2.3.11
    mixCoord:
      replicas: 2
    proxy:
      replicas: 2
    queryNode:
      replicas: 2
      resources:
        requests:
          cpu: '1'
          memory: 8Gi
          ephemeral-storage: 10Gi
        limits:
          cpu: '1'
          memory: 8Gi
          ephemeral-storage: 20Gi
    indexNode:
      replicas: 2
      resources:
        requests:
          cpu: '1'
          memory: 4Gi
          ephemeral-storage: 10Gi
        limits:
          cpu: '1'
          memory: 8Gi
          ephemeral-storage: 20Gi
    # localStorage:
    #   enabled: true
    dataNode:
      replicas: 2
      resources:
        requests:
          cpu: '1'
          memory: 4Gi
          ephemeral-storage: 10Gi
        limits:
          cpu: '1'
          memory: 8Gi
          ephemeral-storage: 20Gi  
  dependencies:
    etcd:
      inCluster:
        values:
          clusterDomain: cluster.local
    msgStreamType: kafka
    kafka:
      inCluster:
        values:
          clusterDomain: cluster.local
          zookeeper:
            enabled: true
            replicaCount: 2
            clusterDomain: cluster.local
    storage:
      external: true
      type: S3
      # Note: you must use regional endpoint here, otherwise the minio client that milvus uses will fail to connect
      endpoint: storage.googleapis.com:443
  config:
    minio:
      cloudProvider: gcp
      bucketName: ai-milvus-bucket
      rootPath: ai-milvus
      useSSL: true
      useIAM: true
    common:
      security:
        authorizationEnabled: true
```

The only difference before and after application is in the image tag part.

**Comment by ian-lss** [comment]
The milvus-operator version is 0.9.8.

**Comment by haorenfsa** [comment]
@ian-lss Thank you! I'll test it again.

**Comment by haorenfsa** [comment]
Not an issue of attu. May due to pod lifecycle problem. Tracking in https://github.com/zilliztech/milvus-operator/issues/88
