### ISSUE TITLE
Error: TypeError: Cannot read properties of undefined (reading 'toJSON')

### ISSUE THREAD

**Issue by seetimee** [zilliztech/attu#444]
milvus最新版本4.0 attu的支持好像还没跟上,这里面用了sparse embedding

**Comment by shanghaikid** [comment]
> milvus最新版本4.0 attu的支持好像还没跟上,这里面用了sparse embedding

Yes. milvus 2.4 was just released this week, attu will support it soon.   
and the 2.4 is still in RC.  attu will support it once it get stable.

**Comment by seetimee** [comment]
thanks

**Comment by Littlecowherd** [comment]
[milvus-2.4.1](https://github.com/milvus-io/milvus/releases/tag/v2.4.1)  has been released. Can ATTU support sparse embedding? Thank you very much.

**Comment by shanghaikid** [comment]
> [milvus-2.4.1](https://github.com/milvus-io/milvus/releases/tag/v2.4.1) has been released. Can ATTU support sparse embedding? Thank you very much.

I hope I can finish this in two weeks.

**Comment by shanghaikid** [comment]
BTW , if you are using docker version, you can try the dev version, sparse embedding is already supported. I am working on the multiple search feature.

**Comment by alexdavis24** [comment]
Has this been addressed in a future release? Thinking of upgrading images to 2.4.8 but wanted to make sure this is resolved (assuming so since the issue is closed but didn't see a related PR)

**Comment by shanghaikid** [comment]
> Has this been addressed in a future release? Thinking of upgrading images to 2.4.8 but wanted to make sure this is resolved (assuming so since the issue is closed but didn't see a related PR)

Yes, it has been fixed in other prs. maybe you can try the app version first.  then upgrade your docker version.
