### ISSUE TITLE
Username and password on login is getting displayed in error message

### ISSUE THREAD

**Issue by Rachit-Chaudhary11** [zilliztech/attu#445]
**Describe the bug:**
This maybe a security breach as login fails with the username and password displayed on the screen.

**Steps to reproduce:**
1. Try to login with wrong credentials
2. Username and passwords are getting displayed in error pop-up

**Attu version:**
v.2.3.8

<img width="1792" alt="Screenshot 2024-03-22 at 5 31 03 PM" src="https://github.com/zilliztech/attu/assets/65501028/3aa38b14-f59a-403b-a26e-cb47a4ca1264">

**Comment by shanghaikid** [comment]
what's your version of milvus?

**Comment by Rachit-Chaudhary11** [comment]
Milvus version is v2.3.3

**Comment by shanghaikid** [comment]
ok, I will test it later.

**Comment by shanghaikid** [comment]
I've tested.  this was a milvus issue, it was fixed in the v2.3.4. you may upgrade your milvus to the latest version, I guess v2.3.12. 

https://github.com/milvus-io/milvus/pull/28428
