### ISSUE TITLE
attu2.3.9 删除自定义数据库，default数据库下的collection不可见

### ISSUE THREAD

**Issue by liangzzong** [zilliztech/attu#467]
**Describe the bug:**
V2.4.0-Rc.1版本的milvus搭配attu2.3.9 ,删除了自定义的数据库时，删除成功后，default数据库下的collection 会出现看不到的情况，重新登录attu才能看到default下的collection

**Steps to reproduce:**
1.
2.
3.

**Attu version:**
2.3.9

**Milvus version:**
V2.4.0-Rc.1

**Comment by shanghaikid** [comment]
Thanks for the ticket, I will fix it soon. 

By the way, attu doesn't support all new features for milvus 2.4 yet.
