### ISSUE TITLE
The login page supports a selection list for Milvus addresses

### ISSUE THREAD

**Issue by douglarek** [zilliztech/attu#473]
**Describe the feature:**
![image](https://github.com/zilliztech/attu/assets/1488134/aabb5e4e-a295-49ff-85ec-c0269611c8f9)

**Describe a specific use case for the feature:**
An organization may require managing many Milvus instances. Some addresses may be using UDNS, which can be long and difficult to remember. Support for this feature requires MILVUS_URL to support comma-separated URLs.

**Comment by shanghaikid** [comment]
I would like to store the user connected addresses, then the next time, user can select these addresses from the dropdown.  Here is the demo:  https://github.com/user-attachments/assets/aa1e5a75-213a-4da0-a7a4-a51df721341f
