### ISSUE TITLE
If the collection hasn't been loaded, querying shouldn't be attempted

### ISSUE THREAD

**Issue by douglarek** [zilliztech/attu#474]
**Describe the bug:**
Insert 100 sample data records on Attu, without loading the collection. After insertion is completed, an error is reported when querying.

![image](https://github.com/zilliztech/attu/assets/1488134/4ffbed5f-b077-48f4-9b5a-c4b047785172)

**Steps to reproduce:**
1. Click on 'Attu' to enter the specific collection.
2.  Insert 100 sample data records and observe the page output.

**Attu version:**
v2.3.8

**Comment by shanghaikid** [comment]
please upgrade to the latest version.
