### ISSUE TITLE
There is no delete collection button

### ISSUE THREAD

**Issue by lironghai** [zilliztech/attu#476]
**Describe the feature:**
There is no delete collection button, will you not delete collection operations on the support page in the future?

**Describe a specific use case for the feature:**

**Comment by shanghaikid** [comment]
in milvus, it uses term 'drop', for example, `drop collection`, `drop user`, `drop database` .

![image](https://github.com/zilliztech/attu/assets/185051/18fc0d72-42a5-4af9-b236-6f1190dca8ba)

**Comment by lironghai** [comment]
> in milvus, it uses term 'drop', for example, `drop collection`, `drop user`, `drop database` .
> 
> ![image](https://private-user-images.githubusercontent.com/185051/322198713-18fc0d72-42a5-4af9-b236-6f1190dca8ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMDUxMTgsIm5iZiI6MTcxMzAwNDgxOCwicGF0aCI6Ii8xODUwNTEvMzIyMTk4NzEzLTE4ZmMwZDcyLTQyYTUtNGFmOS1iMjM2LTZmMTE5MGRjYThiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QxMDQwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzNkNGVkMjcyZGFiMmVjZWYxNzAxODNiOTg4NzcyMmQxYmU4Zjc5MzZhZmU4MmQyOTQzZGFlMWY3Mzk1NGE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WSXNPaZ8Eq4Rq1y8mXi63KiPEnYTqGoyFFN-pPbEUhc)

Thank you, I just saw the default tag
