### ISSUE TITLE
How to terminate a rebuilding index

### ISSUE THREAD

**Issue by douglarek** [zilliztech/attu#477]
**Describe the bug:**

![image](https://github.com/zilliztech/attu/assets/1488134/6834510e-e0f6-41a3-b4c8-7cd0a4cccada)

**Steps to reproduce:**
1.
2.
3.

**Attu version:**

2.3.10
**Attu version:**

**Comment by shanghaikid** [comment]
Maybe you can try `dropIndex` API, but I am not sure.

**Comment by shanghaikid** [comment]
> > Maybe you can try `dropIndex` API, but I am not sure.
> 
> Thank you, but will it be supported on Attu?

If it works, I'm happy to support.
