### ISSUE TITLE
When loading one of the partitions, the status of collection shows an error

### ISSUE THREAD

**Issue by Renekton** [zilliztech/attu#49]
**Describe the bug:**
When loading one of the partitions, the status shows an error

**Steps to reproduce:**
1. create three partitions in one collection， and insert data into each partition separately
![image](https://user-images.githubusercontent.com/7531084/159390539-736bd8f2-b7c2-4122-89e9-67775359acf6.png)

2. load one of the partitions with python sdk

collection = Collection("sp_partiton")      # Get an existing collection.
collection.load(["1"])

3. return the home page of attu, and find that the status of "sp_partion" is wrong
![image](https://user-images.githubusercontent.com/7531084/159391355-fa0cb244-dc2b-4361-b07e-7584b05aab6c.png)

4. check the console log of url "http://#host:port#/api/v1/collections" shows the following：
![image](https://user-images.githubusercontent.com/7531084/159391150-81a712a8-bc1f-4e1d-909d-9e32036dc688.png)

**Attu version:**
2.0.5

**Attu version:**
2.0.5

**Comment by nameczz** [comment]
@Renekton  hi, i think this one is  also Milvus problem. Could you please create issue for Milvus ?
