### ISSUE TITLE
BadRequestError: Connect milvus failed, check your milvus address.

### ISSUE THREAD

**Issue by StevenSama** [zilliztech/attu#50]
**Describe the bug:**
attu can't connect to milvus ,return BadRequestError: Connect milvus failed, check your milvus address. try to connect milvus with milvus_cli will be ok on the same host.

**Steps to reproduce:**
1.docker run -p 8000:3000 -e HOST_URL=http://{ your machine IP }:8000 -e MILVUS_URL={your machine IP}:19530 zilliz/attu:latest
2.click the button try to connect to miluvs some times can connect, some time return back  Connect milvus failed, check your milvus address
3.in the same time try to connect miluvs with milvus_cli can connect success,and list collections ok

**Attu version:**
zilliz/attu:latest

**Attu version:**
zilliz/attu:latest

**Comment by StevenSama** [comment]
![c0c8c643c04bb054cda61e16c326000](https://user-images.githubusercontent.com/6235700/159626924-c50f5cf9-0adc-4bdf-b22b-56cc98925d8b.png)

**Comment by nameczz** [comment]
what do you mean some times can connect, some time return back Connect milvus failed? @StevenSama

**Comment by nameczz** [comment]
milvus_cli also some times can connect, some time return back Connect milvus failed?

**Comment by StevenSama** [comment]
I mean that，the milvus server is healthy but attu canot connect to milvus

**Comment by StevenSama** [comment]
when attu connect to milvus error happen,I try milvus_cli can connect sucessfluy.

**Comment by nameczz** [comment]
So you never connect Milvus successfully in Attu, right?
Is your Attu, Milvus, Milvus_cli running on the same computer?
Like: docker run -p 8000:3000 -e HOST_URL=http://192.168.0.108:8000 -e MILVUS_URL= 192.168.0.108:19530 zilliz/attu:latest

**Comment by StevenSama** [comment]
in attu,some time connect successfully, attu and milvus_cli on the same computer

**Comment by StevenSama** [comment]
Attu can sometimes connect and sometimes can't connect. After pressing F5, there is a high probability that it won't connect.

**Comment by StevenSama** [comment]
Attu is running normally, it will not connect when refreshing or changing another milvus address. At this time, it can be connected normally with milvus_cli on the same host.

**Comment by StevenSama** [comment]
> So you never connect Milvus successfully in Attu, right? Is your Attu, Milvus, Milvus_cli running on the same computer? Like: docker run -p 8000:3000 -e HOST_URL=http://192.168.0.108:8000 -e MILVUS_URL= 192.168.0.108:19530 zilliz/attu:latest

**Comment by nameczz** [comment]
@StevenSama  related issue #68
