### ISSUE TITLE
2

### ISSUE THREAD

**Issue by TonyAnn** [zilliztech/attu#501]
**Describe the bug:**

After the segment is increased to 2GB,

When using attu and scalar filtering, switch to the data option. When no filtering conditions are entered, output_data_size <= limit_size is reported. The proxy.grpc.clientMaxRecvSize parameter defaults to 104857600 and has not been adjusted.

For data scalar filtering, can you add a limit return to avoid throwing errors before each query?

The detailed error report is as follows: 

fail to query on all shard leaders, err=All attempts results: attempt #1:code: UnexpectedError, 

error: fail to Query, QueryNode ID = 51, reason=Query 52 failed, reason err stack trace: /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:369 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:268 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Query /go/src/github.com/milvus-io/milvus/internal/querynode/shard_cluster.go:882 github.com/milvus-io/milvus/internal/querynode.(*ShardCluster).Query.func2 /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit: rpc error: code = Unavailable desc = error reading from server: read tcp 100.115.71.207:54918->100.115.71.215:21123: use of closed network connection attempt #2:code: UnexpectedError, 

error: fail to Query, QueryNode ID = 53, reason=Query 33 failed, reason err stack trace: /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:369 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:268 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Query /go/src/github.com/milvus-io/milvus/internal/querynode/shard_cluster.go:882 github.com/milvus-io/milvus/internal/querynode.(*ShardCluster).Query.func2 /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit: rpc error: code = Canceled desc = context canceled attempt #3:code: UnexpectedError, error: fail to Query, QueryNode ID = 59, reason=Query 59 failed, 

reason [UnexpectedError] Assert "output_data_size <= limit_size" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentInterface.cpp:81 => query results size 1680834480 exceed the limit 104857600 err %!w(<nil>) attempt #4:code: UnexpectedError, error: fail to Query, QueryNode ID = 51, reason=Query 2 failed, reason err stack trace: /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:369 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:268 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Query /go/src/github.com/milvus-io/milvus/internal/querynode/shard_cluster.go:882 github.com/milvus-io/milvus/internal/querynode.(*ShardCluster).Query.func2 /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit: 

rpc error: code = Canceled desc = context canceled attempt #5:code: UnexpectedError, error: fail to Query, QueryNode ID = 14, reason=Query 36 failed, reason err stack trace: /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace /go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:369 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call /go/src/github.com/milvus-io/milvus/internal/distributed/querynode/client/client.go:268 github.com/milvus-io/milvus/internal/distributed/querynode/client.(*Client).Query /go/src/github.com/milvus-io/milvus/internal/querynode/shard_cluster.go:882 github.com/milvus-io/milvus/internal/querynode.(*ShardCluster).Query.func2 /usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit: rpc error: code = Canceled desc = context canceled

**Steps to reproduce:**
1.
2.
3.

**Attu version:**
2.3.10 

**Attu version:**

**Comment by shanghaikid** [comment]
how much entities do you have?  what's your schema?

**Comment by shanghaikid** [comment]
and what's your milvus version?

**Comment by TonyAnn** [comment]
> and what's your milvus version?

milvus version is 2.2.16

**Comment by TonyAnn** [comment]
> how much entities do you have? what's your schema?
entity number is 379882745，schema is simple only id and vector  two fields

**Comment by shanghaikid** [comment]
> > and what's your milvus version?
> 
> milvus version is 2.2.16

milvus 2.2 doesn't support iterator,  that's why your get this error if you have  a lot of entities 
The data view feature in Attu 2.3.10 can't serve 2.2.16 well.  Maybe you should upgrade your milvus server to 2.3.x or downgrade attu.
