### ISSUE TITLE
Created additional semver container tags

### ISSUE THREAD

**Issue by timheuer** [zilliztech/attu#502]
**Describe the feature:**

Right now attu container images are not fully semver. There is `2.3.0-2.3.10 `all the way up in between, but no `2.3` tagged image.  Can you please update to include additional tagged/hosted images on Docker hub that conform to major.minor?

**Describe a specific use case for the feature:**
Our framework uses some image tags as defaults and we'd rather not update every release to 2.x.x and rather would use major.minor binding if possible.  This would help keep revisions updated for our consumers as well.

**Comment by shanghaikid** [comment]
Hi, v2.3 has been pushed. 

![image](https://github.com/zilliztech/attu/assets/185051/13a93cd4-2fdd-4799-801e-72b2430e361e)

We will update the release script later.

**Comment by shanghaikid** [comment]
https://github.com/zilliztech/attu/releases/tag/v2.4.0

v2.4.0 has been released. please try it.

![image](https://github.com/zilliztech/attu/assets/185051/6f172a6c-61ba-4c95-8473-aedebc1ed4e3)
