### ISSUE TITLE
Exporting Chinese characters to Excel with garbled characters and changing IDs

### ISSUE THREAD

**Issue by master006** [zilliztech/attu#503]
![image](https://github.com/zilliztech/attu/assets/25217361/8d03af5d-4e7a-40fd-8afc-97037ccc74a5)

**Comment by shanghaikid** [comment]
can you share you data that I can test? I don't think we have problem about Chinese characters. maybe your data have special characters? 

![image](https://github.com/zilliztech/attu/assets/185051/b4213e5c-8ae4-4cb8-954f-fc23cb2ad9aa)
![image](https://github.com/zilliztech/attu/assets/185051/73f45aa2-5b75-4871-b631-0755087f38d0)
