### ISSUE TITLE
Add support for working behind a proxy at a non-root path

### ISSUE THREAD

**Issue by rmkraus** [zilliztech/attu#505]
**Describe the feature:**
I would like to make Attu available from behind a proxy server and mount Attu to a non-root directory on that proxy server. I could not find a way to specify a proxy-prefix.

**Describe a specific use case for the feature:**
reverse web proxies

**Comment by shanghaikid** [comment]
I tested this on my mac, it works. 

```nginx
server {
  listen 8080;
  server_name localhost;

  location /attu/ {
    proxy_pass http://localhost:3000/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    rewrite ^/attu/(.*)$ /$1 break;
  }
}
```

![image](https://github.com/zilliztech/attu/assets/185051/0fc14318-bf04-439a-8148-cb9de1afa744)
