### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toJSON')

### ISSUE THREAD

**Issue by ebezgodov** [zilliztech/attu#506]
**Describe the bug:**
I have "TypeError: Cannot read properties of undefined (reading 'toJSON')" error when open collection - Data tab. There is on all collections, created by my python app. But there is no error if I create test collection within attu interface.

**Steps to reproduce:**
1. In my python app: col = Collection(COLLECTION_NAME, schema, consistency_level="Strong")
2. In attu interface collection - Data tab.
3. "TypeError: Cannot read properties of undefined (reading 'toJSON')".

**Attu version:**
v 2.3.10
![111](https://github.com/zilliztech/attu/assets/152502496/cd13d5ce-6acd-49f8-b9c9-080960ba58f1)

**Attu version:**

**Comment by RafaelXokito** [comment]
Duplicated issue of #444 .
A possible solution is referenced in this [comment](https://github.com/zilliztech/attu/issues/444#issuecomment-2102479904) by @shanghaikid .
