### ISSUE TITLE
ATTU容器崩溃情况

### ISSUE THREAD

**Issue by zerodeltafeng** [zilliztech/attu#508]
**Describe the bug:**
ATTU运行的容器在ATTU UI界面对collection加载操作后崩溃。同样步骤问题重现三次，每次必出。
![image](https://github.com/zilliztech/attu/assets/35525901/3d1a4209-0dd2-448e-9f9e-d17bcc9094f1)

**Steps to reproduce:**
1.启动standalone的milvus本地向量数据库；
2.执行简单的链接和创建collection的python代码段，片段如下：
try:
    connections.connect(alias="default", user="root", host="172.27.16.206", port="19530")
except Exception as e:
    logger.error("Failed to connect to Milvus database. Error: %s", str(e))
    raise Exception("Failed to connect to Milvus database.")

collection_name = "image_store1"

fields = [
    FieldSchema(name="id", dtype=DataType.INT64, is_primary=True, auto_id=True),
    FieldSchema(name="embedding", dtype=DataType.FLOAT_VECTOR, dim=1000),
    FieldSchema(name="image_path", dtype=DataType.VARCHAR, max_length=1024)
]
schema = CollectionSchema(fields=fields, description="Collection for image embeddings")

try:
    if not utility.has_collection(collection_name):
        collection = Collection(
            name=collection_name,
            schema=schema,
            using='default',
            shards_num=2,
            consistency_level="Strong"
        )
        index_params = {
            "index_type": "HNSW",
            "metric_type": "COSINE",
            "params": {"M": 8, "efConstruction": 64}
        }
        collection.create_index(field_name="embedding", index_params=index_params)

except Exception as e:
    logger.error("Failed to create or access the collection. Error: %s", str(e))
    raise Exception("Failed to create or access the collection.")

3.在ATTU UI界面手动中点击加载collection按钮后，容器崩溃。手动start 容器镜像后再次进入UI，显示已加载。

**Attu version:**
milvusdb/milvus:v2.4.0
zilliz/attu:v 2.3.10

**Attu version:**

**Comment by shanghaikid** [comment]
attu 2.3.10 doesn't support milvus 2.4.
