### ISSUE TITLE
Attu Login issue 

### ISSUE THREAD

**Issue by ShivamGuptaHat** [zilliztech/attu#514]
**Describe the bug:**
I am from Walmart's element team. Attu is being used to access milvus instance. Recently we have found one issue.
One login session being used in different computer system. For example, I logged-in with userId-1 in system-1 after that I logged-in with userId-2 in system-2. Now if I refresh system-1 then it also shows being logged-in as user-2. That means most recent login session being used across different systems. 

**Steps to reproduce:**
1. Login as read-only-user in system-1. _read-only-user should not be able to create collection in any database._
2. Login as read-write-user in system-2. _read-write-user should be able to create collection in any database._
3. Refresh system-1, Now you can see system-1 shares login session of read-write-user and you should be able to create collection in system-1.

**Attu version:**
v2.3.0

**Attu version:**
v2.3.0

**Comment by shanghaikid** [comment]
thanks, I will check that.

**Comment by shanghaikid** [comment]
can you upgrade your attu to the latest version?

**Comment by ShivamGuptaHat** [comment]
okay I will do that and update you here.

**Comment by ShivamGuptaHat** [comment]
Seems it is fixed in attu version 2.4.0.
Just have one question, Is attu version 2.4.0 compatible with milvus 2.4.1 ?

**Comment by shanghaikid** [comment]
> Seems it is fixed in attu version 2.4.0. Just have one question, Is attu version 2.4.0 compatible with milvus 2.4.1 ?

Yes.
