### ISSUE TITLE
show collection properties on collection overview page

### ISSUE THREAD

**Issue by shanghaikid** [zilliztech/attu#517]
User should be able to see `ttl` `mmap` on the collection overview page

**Comment by xige-16** [comment]
It is recommended to add a page for properties to support dynamic modification

**Comment by xige-16** [comment]
I would like to add a function to control the collection rate limit. If possible, it can be set in the properties page.

**Comment by shanghaikid** [comment]
> I would like to add a function to control the collection rate limit. If possible, it can be set in the properties page.

what is the rate limit property? how can I do it with pymilvus?

**Comment by xige-16** [comment]
> > I would like to add a function to control the collection rate limit. If possible, it can be set in the properties page.
> 
> what is the rate limit property? how can I do it with pymilvus?

collection.set_property({key:value})
