### ISSUE TITLE
Blank page when clicking on "Vector Search"

### ISSUE THREAD

**Issue by stephen37** [zilliztech/attu#519]
**Describe the bug:**
Hey, 

When you are in the view of the Collection Overview, if you click on the button "Vector Search" next to the status of the collection, it will redirect you to a blank page and won't load anything. The solution to fix that is to restart Attu. 
This doesn't happen if if click on Vector Search next to the "Overview" button. 

**Steps to reproduce:**
1. Connect to Milvus DB
2. Click on an exisiting collection you have 
3. In the Overview tab, next to "status", click on the "Vector Search" button. 

**Attu version:**
2.4.0

<img width="1204" alt="image" src="https://github.com/zilliztech/attu/assets/6506810/fc80fef1-809a-46a0-b8be-61c0af403f05">

**Comment by shanghaikid** [comment]
Oh, electron version's problem.
