### ISSUE TITLE
unable connect to milvus v2.4.4 by attu v2.4.0

### ISSUE THREAD

**Issue by Monster880** [zilliztech/attu#526]
how to fix it

**Attu version:**
2.4.0

**Milvus version:**
2.4.4

**Comment by Monster880** [comment]
@shanghaikid

**Comment by shanghaikid** [comment]
please provide details

**Comment by Monster880** [comment]
I find it is network proxy problem. The proxy change ip addr and attu can not connect to milvus by localhost ip
