### ISSUE TITLE
Unable to perform vector retrieval

### ISSUE THREAD

**Issue by douglarek** [zilliztech/attu#536]
**Describe the bug:**

Some fields are empty strings, not sure if they are related.

![图片](https://github.com/zilliztech/attu/assets/1488134/7e762b54-d505-4f49-ab45-98778958c16c)

![图片](https://github.com/zilliztech/attu/assets/1488134/aa5e98eb-026b-40af-b364-5302e9a528aa)

![图片](https://github.com/zilliztech/attu/assets/1488134/daa82bfd-edb7-4750-becf-64d0dc82f61b)

![图片](https://github.com/zilliztech/attu/assets/1488134/89b39614-4274-4540-981c-dbc92958795a)

**Steps to reproduce:**
1. 
2.
3.

**Attu version:**

Both v2.4.0 & v2.4.1 don't work, but v2.3.10 does.

**Comment by shanghaikid** [comment]
I will investigate it soon.

**Comment by shanghaikid** [comment]
it's nothing to do with the `varchar` fields.  it is a compatibility issue between 2.4 and 2.3. I will fix this in the v2.4.2. 
attu could use the old api to search on v2.3 if you only do single vector search.

**Comment by shanghaikid** [comment]
you still can use the old search page for now.
