### ISSUE TITLE
Long digit types display abnormally on the interface, losing accuracy

### ISSUE THREAD

**Issue by yushengliao** [zilliztech/attu#542]
The accuracy of the last two digits of the id value in the screenshot is lost, and all the last two digits of the id value are replaced with '00'
These values are actually unique and can be searched correctly, only displaying errors on the UI interface of ATTU
Possible reason: The number type in JavaScript ranges from -2 ^ 53 to 2 ^ 53

![image](https://github.com/zilliztech/attu/assets/29765903/45465d14-9651-4713-b6df-7fedf6732f9e)

**Comment by shanghaikid** [comment]
You are correct, in javascript, there is no int64. therefore I have no way to fix this.
