### ISSUE TITLE
Reset invalid properties

### ISSUE THREAD

**Issue by xige-16** [zilliztech/attu#547]
**Describe the bug:**
reset properties set property's value to "". When the server parses it, it will consider it an invalid value. Although it will not cause the server to crash, it will print a lot of warning logs.
https://github.com/zilliztech/attu/blob/97c6c4e8a8f085bf5e1cf5b8ad8efa3cfb82feed/client/src/pages/dialogs/ResetPropertyDialog.tsx#L22-L25

**Steps to reproduce:**
1.
2.
3.

**Attu version:**

**Attu version:**

**Comment by xige-16** [comment]
https://github.com/milvus-io/milvus/blob/2a1356985dd3683990e3390f3070b9ea020c7d08/internal/rootcoord/util.go#L188-L196

**Comment by shanghaikid** [comment]
so how to reset it?

**Comment by xige-16** [comment]
> so how to reset it?

set number property to -1, the server will use the default setting. 
For a bool property, reset to false?

**Comment by shanghaikid** [comment]
I think milvus should change it's code.  if I set it to an empty string, it should delete the key in the memory.

**Comment by shanghaikid** [comment]
You can open a ticket to the milvus team.  : )

**Comment by xige-16** [comment]
ha ha
