### ISSUE TITLE
Error: 13 INTERNAL: No message received

### ISSUE THREAD

**Issue by zhongyuan-cn** [zilliztech/attu#565]
After I write to the collection, I use Attu to query and report an error.

<img width="1247" alt="111" src="https://github.com/zilliztech/attu/assets/22765665/a976ea6a-bd78-4e66-94a1-c9c6cf0f7777">

When I click on the data, return the error message as shown in the figure，Please help me , thank you.
I am using Windows Client
milvus 2.4.5
attu 2.4.2

**Comment by shanghaikid** [comment]
I think you should check milvus logs. is your milvus alive?
