### ISSUE TITLE
Uncaught promise type error: Cannot read 'search' from undefined

### ISSUE THREAD

**Issue by Jacobh2** [zilliztech/attu#57]
**Describe the bug:**
I've created a new collection with 2 fields: primary key and embedding. I've created a HNSW_PQ index on it and then loaded it into memory. I then port-forward to my Attu instance and when I try to use the search function I get this error in the console log:

http://localhost:3000/#/search

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'search')
    at SearchParams.tsx:59:39
    at Object.Io [as useMemo] (react-dom.production.min.js:168:377)
    at t.useMemo (react.production.min.js:23:113)
    at t.default (SearchParams.tsx:56:24)
    at oo (react-dom.production.min.js:157:137)
    at Ho (react-dom.production.min.js:180:154)
    at Ws (react-dom.production.min.js:269:343)
    at wl (react-dom.production.min.js:250:347)
    at Al (react-dom.production.min.js:250:278)
    at Nl (react-dom.production.min.js:250:138)
```

**Steps to reproduce:**
1. Create collection
2. Load embeddings
3. Create HNSW_PQ index
4. Load the index
5. At Attu startpage where it then shows the loaded collections, click "Vector search". The screen glitches and then goes blank. 

**Attu version:**
2.0.5

**Comment by nameczz** [comment]
Attu did not support HNSW_PQ index yet. It will cause this bug. 
![image](https://user-images.githubusercontent.com/20559208/166212510-08bdd4be-7997-4eb1-a1c4-1d149aa97f66.png)

You can  do vector search when you create these index on FloatVector field.
In next version, we will support more index in Attu, and fix this bug.

**Comment by Jacobh2** [comment]
Thank you for the reply and info! Maybe it would be nice to handle the non-supported indices in a more graceful way? With a pop-up or something?
