### ISSUE TITLE
Nginx反向代理且Milvus开启认证后无法完成登录

### ISSUE THREAD

**Issue by Ccccx** [zilliztech/attu#571]
**Describe the bug:**
I used nginx for reverse proxy attu (configured using the example in README), and Milvus turned on login authentication. Pages can be normal open, but open authentication input account and password and then click the connect button no response, after observation the request that launch via a browser request path is: https://****.cn/api/v1/milvus/connect, reverse proxy prefix is lost.

**Steps to reproduce:**
1. Milvus enabled certification
2. sudo docker run -d -p 18000:3000 --network=milvus -e MILVUS_URL=standalone:19530 zilliz/attu:v2.4
3.Configuring a reverse proxy：

  location /attu/ {
    proxy_pass http://localhost:3000/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    rewrite ^/attu/(.*)$ /$1 break;
  }

**Attu version:**
v2.4

**Comment by shanghaikid** [comment]
I will test it tomorrow.

**Comment by shanghaikid** [comment]
What's your target? 
`https://****.cn/` or `https://****.cn/attu` ?

**Comment by Ccccx** [comment]
> What's your target? `https://****.cn/` or `https://****.cn/attu` ?

https://****.cn/attu

**Comment by shanghaikid** [comment]
please upgrade to the v2.4.4 and follow this doc, I think it should be working. 

https://github.com/zilliztech/attu/blob/main/doc/use-attu-behind-proxy.md
