### ISSUE TITLE
collection中的数据自动增加

### ISSUE THREAD

**Issue by wzh28x** [zilliztech/attu#573]
**Describe the bug:**
通过代码往collection中插入了110条数据，过了一段时间就变成330条

**Steps to reproduce:**
1.
2.
3.

**Attu version:**

**Attu version:**

**Comment by shanghaikid** [comment]
请检查一下您的代码是否正确，并且同一时间是否有其他人插入数据。 attu不会处理milvus的数据。

**Comment by wzh28x** [comment]
> 请检查一下您的代码是否正确，并且同一时间是否有其他人插入数据。 attu不会处理milvus的数据。

我在attu把数据清了，又插入了一次，中间没有任何操作，过一段时间看变成440

**Comment by shanghaikid** [comment]
> > 请检查一下您的代码是否正确，并且同一时间是否有其他人插入数据。 attu不会处理milvus的数据。
> 
> 我在attu把数据清了，又插入了一次，中间没有任何操作，过一段时间看变成440

你的一致性是什么？  参考 https://milvus.io/docs/consistency.md

**Comment by wzh28x** [comment]
> > > 请检查一下您的代码是否正确，并且同一时间是否有其他人插入数据。 attu不会处理milvus的数据。
> > 
> > 
> > 我在attu把数据清了，又插入了一次，中间没有任何操作，过一段时间看变成440
> 
> 你的一致性是什么？ 参考 https://milvus.io/docs/consistency.md

Strong

**Comment by shanghaikid** [comment]
你用api查出来的是对的吗？

**Comment by wzh28x** [comment]
> 你用api查出来的是对的吗？

我是在attu上面看的数据

**Comment by shanghaikid** [comment]
> > 你用api查出来的是对的吗？
> 
> 我是在attu上面看的数据

你需要确认api出来的数据和attu出来的结果是否一样。  一般来说，attu不会有问题，如果数据不正确，你可能需要去milvus的repo提issue。 

PS，milvus和attu的版本是什么？

**Comment by wzh28x** [comment]
> > > 你用api查出来的是对的吗？
> > 
> > 
> > 我是在attu上面看的数据
> 
> 你需要确认api出来的数据和attu出来的结果是否一样。 一般来说，attu不会有问题，如果数据不正确，你可能需要去milvus的repo提issue。
> 
> PS，milvus和attu的版本是什么？

数据插入时返回的信息显示插入了110条，在attu上面也是110条，就是过了段时间就不对了，milvus是2.4.5，attu是2.4.3

**Comment by shanghaikid** [comment]
> > > > 你用api查出来的是对的吗？
> > > 
> > > 
> > > 我是在attu上面看的数据
> > 
> > 
> > 你需要确认api出来的数据和attu出来的结果是否一样。 一般来说，attu不会有问题，如果数据不正确，你可能需要去milvus的repo提issue。
> > PS，milvus和attu的版本是什么？
> 
> 数据插入时返回的信息显示插入了110条，在attu上面也是110条，就是过了段时间就不对了，milvus是2.4.5，attu是2.4.3

根据目前的这些描述我无法重现你的问题。   你有很多collection吗？你重启attu还会这样吗？

**Comment by wzh28x** [comment]
> > > > > 你用api查出来的是对的吗？
> > > > 
> > > > 
> > > > 我是在attu上面看的数据
> > > 
> > > 
> > > 你需要确认api出来的数据和attu出来的结果是否一样。 一般来说，attu不会有问题，如果数据不正确，你可能需要去milvus的repo提issue。
> > > PS，milvus和attu的版本是什么？
> > 
> > 
> > 数据插入时返回的信息显示插入了110条，在attu上面也是110条，就是过了段时间就不对了，milvus是2.4.5，attu是2.4.3
> 
> 根据目前的这些描述我无法重现你的问题。 你有很多collection吗？你重启attu还会这样吗？

目前就一个，没试过重启

**Comment by shanghaikid** [comment]
> > > > > > 你用api查出来的是对的吗？
> > > > > 
> > > > > 
> > > > > 我是在attu上面看的数据
> > > > 
> > > > 
> > > > 你需要确认api出来的数据和attu出来的结果是否一样。 一般来说，attu不会有问题，如果数据不正确，你可能需要去milvus的repo提issue。
> > > > PS，milvus和attu的版本是什么？
> > > 
> > > 
> > > 数据插入时返回的信息显示插入了110条，在attu上面也是110条，就是过了段时间就不对了，milvus是2.4.5，attu是2.4.3
> > 
> > 
> > 根据目前的这些描述我无法重现你的问题。 你有很多collection吗？你重启attu还会这样吗？
> 
> 目前就一个，没试过重启

那就更不科学了。。。 要不你删了重新试试？

**Comment by wzh28x** [comment]
> > > > > > > 你用api查出来的是对的吗？
> > > > > > 
> > > > > > 
> > > > > > 我是在attu上面看的数据
> > > > > 
> > > > > 
> > > > > 你需要确认api出来的数据和attu出来的结果是否一样。 一般来说，attu不会有问题，如果数据不正确，你可能需要去milvus的repo提issue。
> > > > > PS，milvus和attu的版本是什么？
> > > > 
> > > > 
> > > > 数据插入时返回的信息显示插入了110条，在attu上面也是110条，就是过了段时间就不对了，milvus是2.4.5，attu是2.4.3
> > > 
> > > 
> > > 根据目前的这些描述我无法重现你的问题。 你有很多collection吗？你重启attu还会这样吗？
> > 
> > 
> > 目前就一个，没试过重启
> 
> 那就更不科学了。。。 要不你删了重新试试？

我刚刚又发现，我通过代码把表清空了，然后确认了表里没数据，也没有其他操作，过了一段时间数据又回来了
