### ISSUE TITLE
mac arm 版本无法打开

### ISSUE THREAD

**Issue by bigshi** [zilliztech/attu#576]
**Describe the bug:**

“attu”已损坏，无法打开。 你应该将它移到废纸篓。

Apple M2 Max   macOS Ventura版本13.4 (22F66)

**Steps to reproduce:**

**Attu version:**
attu-mac-arm64-v2.4.3.dmg
attu-mac-arm64-v2.4.2.dmg

**Comment by bigshi** [comment]
![Xnip2024-07-15_17-59-14](https://github.com/user-attachments/assets/012dff29-9a05-4834-9f91-04eb4cc29c79)
![Uploading Xnip2024-07-15_17-59-28.jpg…]()

**Comment by zhanshuyou** [comment]
@bigshi 
enter this command in the command line.
`sudo xattr -rd com.apple.quarantine /Applications/attu.app`
