### ISSUE TITLE
Attu cannot access milvus

### ISSUE THREAD

**Issue by Zzt1993** [zilliztech/attu#58]
**Describe the bug:**
Attu cannot access milvus

**Steps to reproduce:**
1.
2.
3.

**Attu version:**
![94e6fc865dda326809642496f71a906](https://user-images.githubusercontent.com/95836616/167235808-88750f0d-0d63-48e1-8b79-6e3aa4fb96a6.png)
![2d8d59ef57bfc135ff954aef1d4ceb1](https://user-images.githubusercontent.com/95836616/167235815-94b2f6d4-ec64-4ff1-8c6d-4e352358990b.png)
helm install my-release milvus/milvus --set attu.enabled=true

kubectl edit svc my-release-milvus-attu
![image](https://user-images.githubusercontent.com/95836616/167235846-8fe592cf-8bb7-43a3-ad57-82c6d19d9c31.png)

**Attu version:**

**Comment by nameczz** [comment]
We have doc about how to use attu in helm. https://milvus.io/docs/v2.0.x/attu_install-helm.md 
Try to follow this doc, may be can solve your problem.

**Comment by Zzt1993** [comment]
I operate according to the official website and expose the ingress service in the k8s cluster through nodeport. I can't access the cluster(https://milvus.io/docs/v2.0.x/attu_install-helm.md)

**Comment by nameczz** [comment]
Did you set local host for attu? 
like: 
<img width="969" alt="image" src="https://user-images.githubusercontent.com/20559208/167242730-0003a4ce-2c02-4ae1-83e9-6b946b3f8f57.png">

**Comment by Zzt1993** [comment]
my ingress not have adderss
![image](https://user-images.githubusercontent.com/95836616/167242779-39fc5e8b-0752-4a76-8fdf-524db6026d76.png)

**Comment by Zzt1993** [comment]
![image](https://user-images.githubusercontent.com/95836616/167242850-2f69f456-7d19-418b-a48a-f853dc25a2b7.png)

**Comment by Zzt1993** [comment]
The inress operation on your official website can only be accessed within the k8s cluster, not for external access. After I expose it through the service, I can access the Attu service externally

**Comment by Zzt1993** [comment]
The inress operation on your official website can only be accessed within the k8s cluster, not for external access. After I expose it through the service, I can access the Attu service externally

**Comment by nameczz** [comment]
I'm not familiar with helm settings. @Bennu-Li can give some help about this.

**Comment by Bennu-Li** [comment]
Your attu service type is NodePort? If so, try to disable the ingress: `--set attu.ingress.enabled=false`.

**Comment by Bennu-Li** [comment]
You are not actually accessing attu through the ingress service, but through the service provided by NodePort.
In attu there is an environment variable HOST_URL with a value of my-release-milvus-attu:3000. in your example, since you changed the service type of the attu service to NodePort, the actual value of HOST_URL should be 193.168.57.213:31675. We do not recommend setting the attu service type to NodePort.
If you want to do so, try to change the HOST_URL value to 'my-release-milvus-attu:31675'
```
kubectl edit deployment my-release-milvus
```
And then configure DNS in /etc/hosts:
```
193.168.57.213 my-release-milvus-attu
```

**Comment by wutachiang** [comment]
> I operate according to the official website and expose the ingress service in the k8s cluster through nodeport. I can't access the cluster(https://milvus.io/docs/v2.0.x/attu_install-helm.md)

Did you solve this problem please? I also encountered attu unable to access milvus k8s cluster service.

**Comment by Zzt1993** [comment]
单独起一个docker进程：
docker run -d -p 8000:3000 -e HOST_URL=http://本机:8000 -e MILVUS_URL=K8S集群的vip:svc暴露的端口31063 zilliz/attu:latest
这样就可以解决了

**Comment by kaonick** [comment]
If milvus install in Windows-WSL，
Docker should run by:
docker run -d -p 8000:3000 -e HOST_URL=[http://localhost:8000](http://xn--8pv2a:8000/) -e MILVUS_URL=_**vEvthernet(WSL) IP**_:19530 zilliz/attu:latest

**Comment by nameczz** [comment]
related issue #68
