### ISSUE TITLE
配置域名访问

### ISSUE THREAD

**Issue by liucheng-lch** [zilliztech/attu#585]
**Describe the feature:**

连接到Milvus服务器的地址希望是通过域名来连接
**Describe a specific use case for the feature:**
![image](https://github.com/user-attachments/assets/368967f2-4dda-4c31-a76d-69852e47dc4f)

已在milvs.yaml配置
![image](https://github.com/user-attachments/assets/6767ca6a-178c-4f51-8c12-2d88eae71617)

这样配置不行，
milvs是否可以通过域名来连接

**Comment by shanghaikid** [comment]
这个和attu无关，这个是网络问题。如果你是docker启动的attu。 你这个域名在attu container里面是否能通？

**Comment by liucheng-lch** [comment]
是可以ping通的

**Comment by shanghaikid** [comment]
你确定在docker内部的dns可以正确解析你这个域名？ 

如果可以的话，报什么错？ 日志有吗？

**Comment by liucheng-lch** [comment]
![image](https://github.com/user-attachments/assets/07266ab8-10ae-4257-bf76-f2e26537285a)
报这个
