### ISSUE TITLE
attu v2.4.2+ on mac arm64 is broken

### ISSUE THREAD

**Issue by Corazon0513** [zilliztech/attu#591]
**Describe the bug:**
<img width="260" alt="image" src="https://github.com/user-attachments/assets/516eedef-b562-4606-983d-b9c3fd4e7092">
I tried v2.4.[2,3,4], they can't execute on my MacBook Pro with M1 Pro SoC. My system version is 14.5 (23F79).
But lucky, v2.4.1 is working.

**Steps to reproduce:**
1. Download dmg file
2. Open dmg and open attu application

**Attu version:**
v.2.4.2 and after mac-arm64 version.

**Comment by shanghaikid** [comment]
We don't have certificate yet. So please use this command to fix this? 

```bash
  sudo xattr -rd com.apple.quarantine /Applications/attu.app
```

**Comment by Corazon0513** [comment]
> We don't have certificate yet. So please use this command to fix this?
> 
> ```shell
>   sudo xattr -rd com.apple.quarantine /Applications/attu.app
> ```

Ouch, I just found that Readme is mentioned this problem, Thanks for your reply!👍

**Comment by Corazon0513** [comment]
resolved
