### ISSUE TITLE
attu cannot login but milvus server fine

### ISSUE THREAD

**Issue by yinnxinn** [zilliztech/attu#605]
**Describe the bug:**
![image](https://github.com/user-attachments/assets/f9461124-4f24-4919-b4fe-fa8f2984d790)

![image](https://github.com/user-attachments/assets/4b0f1b7a-ad5f-46df-a5a6-3c4c0fbfe863)

**Steps to reproduce:**
1. run milvus using docker-compose
2. run attu standalone
3. visualize the system

**Attu version:**
zilliz/attu           v2.4
**Attu version:**

**Comment by shanghaikid** [comment]
The `localhost:19530` can not be visited from the attu docker container. please use the ip that is accessible from the container.

**Comment by yinnxinn** [comment]
邮件已收到，谢谢
