### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by zy465009972** [zilliztech/attu#607]
**Describe the bug:**
windows 打不开Attu，弹这个框，进入页面一直连不上。尝试了重装、重启都不行，3000端口也没有被占用。

**Steps to reproduce:**
1.
![企业微信截图_17223529843528](https://github.com/user-attachments/assets/5d876b3a-da38-4dab-9e77-6ce0a34c437e)

2.
3.

**Attu version:**

**Attu version:**

**Comment by shanghaikid** [comment]
以管理员身份运行应用程序：
在 Windows 上，有时应用程序需要管理员权限才能绑定到某些端口。尝试以管理员身份运行你的 Electron 应用程序。

检查防火墙设置：
确保 Windows 防火墙没有阻止你的应用程序访问 0.0.0.0:3000。你可以尝试临时关闭防火墙以测试是否是防火墙的问题。

检查端口占用：
你可以使用以下命令检查端口 3000 是否被其他进程占用：

```sh
netstat -ano | findstr :3000
```

**Comment by zy465009972** [comment]
非常感谢！但是您提供的这三种方式我都试过了，还是不行。
我用了管理员方式运行、防火墙也关闭了，3000端口也没有占用。
我现在通过docker的方式在使用，但是本地这个报错一直解决不了。


另外您知道怎么修改本地Attu启动的端口吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zilliztech/attu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月31日(星期三) 中午11:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zilliztech/attu] A JavaScript error occurred in the main process (Issue #607)





 
以管理员身份运行应用程序：
 在 Windows 上，有时应用程序需要管理员权限才能绑定到某些端口。尝试以管理员身份运行你的 Electron 应用程序。
 
检查防火墙设置：
 确保 Windows 防火墙没有阻止你的应用程序访问 0.0.0.0:3000。你可以尝试临时关闭防火墙以测试是否是防火墙的问题。
 
检查端口占用：
 你可以使用以下命令检查端口 3000 是否被其他进程占用：
 netstat -ano | findstr :3000

**Comment by shanghaikid** [comment]
app无法修改端口。。。 我们这边试了windows 10，是可以的。 我不确定你的环境有什么不同：（

**Comment by zy465009972** [comment]
之前我用着是没问题的，昨晚重启一下电脑之后突然就不行了。各种办法都试了没用。我用另外一台windows电脑使用也没问题，确实很诡异，我有点怀疑是不是注册表什么信息出错了，卸载是不会删除注册表信息的吧。
目前就先用docker启动的吧。谢谢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zilliztech/attu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月31日(星期三) 中午11:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zilliztech/attu] A JavaScript error occurred in the main process (Issue #607)





 
app无法修改端口。。。 我们这边试了windows 10，是可以的。 我不确定你的环境有什么不同：（

**Comment by shanghaikid** [comment]
如果你真的需要可以自己build打包，就是有点麻烦。
