### ISSUE TITLE
Can we release a new version without HIGH/CRITICAL CVEs?

### ISSUE THREAD

**Issue by weiZhenkun** [zilliztech/attu#622]
https://github.com/zilliztech/attu/pull/515/files, this PR fixes the CVEs of axios packages, can we release a new version without CVEs?

**Comment by shanghaikid** [comment]
I will release one in two days.

**Comment by weiZhenkun** [comment]
Thanks for your great help.

**Comment by shanghaikid** [comment]
new version released.  https://github.com/zilliztech/attu/releases/tag/v2.4.7

**Comment by weiZhenkun** [comment]
So could you help build into helm?
