### ISSUE TITLE
GUI Authentication for Attu

### ISSUE THREAD

**Issue by aruna0710** [zilliztech/attu#647]
**Describe the feature:**
I am deploying milvus using Milvu's official helm chart. I have GUI for Attu. I need to set Auth.

**Describe a specific use case for the feature:**
I am using milvus's official helm chart. How shall I enable auth on Attu gui? Right now without entering username/password if i click on connect, anyone can connect to the milvus db's gui. In the helm chart, in values.yaml, there is no section called "auth" for Attu.

**Comment by shanghaikid** [comment]
attu doesn't have its own authentication system,  it depends on milvus, please refer to this doc: 

https://milvus.io/docs/authenticate.md

**Comment by aruna0710** [comment]
> attu doesn't have its own authentication system, it depends on milvus, please refer to this doc:
> 
> https://milvus.io/docs/authenticate.md

https://github.com/zilliztech/milvus-helm/blob/master/charts/milvus/values.yaml I am using this there is no separate milvus.yaml

**Comment by shanghaikid** [comment]
```
  auth:
    rbac:
      enabled: false

```

I guess set the `rbac` to true, but I am not sure, maybe you can try it.
