### ISSUE TITLE
attu2.3.5在macos15下无法启动，升级2.4.8后无法连接

### ISSUE THREAD

**Issue by conorwong-github** [zilliztech/attu#649]
**Describe the bug:**

attu2.3.5在macos15下无法启动，升级2.4.8后无法连接2.3.x的milvus

**Steps to reproduce:**
1. 升级macos 15
2. attu2.3.5打不开了
3. 升级attu2.4.8发现无法连接到2.3.x的milvus实例上去
![image](https://github.com/user-attachments/assets/3cc2f3a5-15e8-4bd5-a5c6-9661a297f94d)
**Attu version:**

2.4.8
**Attu version:**

**Comment by shanghaikid** [comment]
是的 ，请不要用2.4的attu连接2.3的milvus，有不兼容的情况在。

**Comment by conorwong-github** [comment]
2.3.5会有后续更新 支持 macos15吗？

**Comment by shanghaikid** [comment]
> 2.3.5会有后续更新 支持 macos15吗？

15肯定会支持。 2.3.5就不会了，推荐使用2.4。  或者使用docker版本。
