### ISSUE TITLE
配置推荐的接口或公式

### ISSUE THREAD

**Issue by llllazy** [zilliztech/attu#650]
**Describe the feature:**
希望可以获取这个计算配置页面的计算公式或者接口 https://milvus.io/tools/sizing
直接传参后返回推荐的配置

**Describe a specific use case for the feature:**
内部用户较多，对于向量数据库理解有限，想内部简化下推荐几个常用配置，所以想 调用接口或根据计算公式 ，得到官方建议后 再推荐配置

**Comment by shanghaikid** [comment]
这个和attu没有关系。 sizing tool的代码在这里。 
https://github.com/milvus-io/milvus.io/blob/master/src/pages/tools/sizing.tsx

如果你需要更详细的推荐，欢迎去milvus的repo提问。
