### ISSUE TITLE
attu-mac-arm64-v2.4.8.dmg doesn't work on macOS Sequoia

### ISSUE THREAD

**Issue by jorge-jrzz** [zilliztech/attu#656]
**Describe the bug:**
The file for downloading the Mac desktop application does not work on Sequoia OS version 15.0.

**Steps to reproduce:**
1. Download the file for install Desktop Application in the [Release apart](https://github.com/zilliztech/attu/releases/tag/v2.4.8)
2. Open the downloaded file and install the application:
<img width="400" alt="image" src="https://github.com/user-attachments/assets/c4a89eec-c5c4-4036-991f-9e37f0f2ae9a">

3. Once the application is installed, when open it, this window appears, which makes it impossible to finish the attu download.
![image](https://github.com/user-attachments/assets/037409f8-0a03-4ff6-98d4-f8cf3ee15701)

**Attu version:**
v2.4.8

**Device details:**
- Chip: Apple M1
- Memory: 8 GB
- macOS: 15.0 (24A335)

**Comment by shanghaikid** [comment]
sudo xattr -rd com.apple.quarantine /Applications/attu.app

**Comment by jorge-jrzz** [comment]
> sudo xattr -rd com.apple.quarantine /Applications/attu.app

Excellent, it worked.
