### ISSUE TITLE
When Docker runs the attu tool, the uv_thread_create function is part of the libUV library and is used to create threads in Node.js. The call to this function failed, causing the assertion check to fail and triggering a program crash

### ISSUE THREAD

**Issue by 1850772210** [zilliztech/attu#659]
**Describe the bug:**
docker启动attu工具时遇到node[1]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb9c1f0 node::Abort() [node]
 2: 0xb9c26e  [node]
 3: 0xc0a17e  [node]
 4: 0xc0a261 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xb58213 node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [node]
 6: 0xb5886b node::Start(int, char**) [node]
 7: 0x7702bcd4f24a  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7702bcd4f305 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xad789e _start [node]

**Steps to reproduce:**
1.
2.
3.

**Attu version:**
2.4.8

**Attu version:**

**Comment by shanghaikid** [comment]
what is your docker version?

**Comment by 1850772210** [comment]
> what is your docker version?

I have tried both versions 17.06 and 20.10 of Docker

**Comment by 1850772210** [comment]
> what is your docker version?

我尝试了ubuntu20.04和docker17.06组合 并且尝试了ubuntu24.04和docker20.10组合

**Comment by 1850772210** [comment]
> what is your docker version?

I tried combining Ubuntu 20.04 with Docker 17.06 and Ubuntu 24.04 with Docker 20.10

**Comment by shanghaikid** [comment]
maybe you can try https://hub.docker.com/r/bitnami/attu first.

**Comment by 1850772210** [comment]
> maybe you can try https://hub.docker.com/r/bitnami/attu first.

I tried Bitnami's attu image but still got the same error. Is this related to my two servers Ubuntu24 and Ubuntu22.04

**Comment by shanghaikid** [comment]
> > maybe you can try https://hub.docker.com/r/bitnami/attu first.
> 
> I tried Bitnami's attu image but still got the same error. Is this related to my two servers Ubuntu24 and Ubuntu22.04

I guess it is. you can try to build yourself with a newer node version, change two places with `node:22-slim` , I don't have your system, if it works, A pull request is highly welcomed.

`https://github.com/zilliztech/attu/blob/main/Dockerfile`

**Comment by 1850772210** [comment]
> I guess it is. you can try to build yourself with a newer node version, change two places with `node:22-slim` , I don't have your system, if it works, A pull request is highly welcomed.
> 
> `https://github.com/zilliztech/attu/blob/main/Dockerfile`

Thank you, I'll give it a try. I'm still a beginner, may I ask what operating system you're using

**Comment by shanghaikid** [comment]
> > I guess it is. you can try to build yourself with a newer node version, change two places with `node:22-slim` , I don't have your system, if it works, A pull request is highly welcomed.
> > `https://github.com/zilliztech/attu/blob/main/Dockerfile`
> 
> Thank you, I'll give it a try. I'm still a beginner, may I ask what operating system you're using

I am using mac. but many users are using ubuntu 20.

**Comment by 1850772210** [comment]
> I am using mac. but many users are using ubuntu 20.

Thank you very much. I will try to solve this problem

**Comment by 1850772210** [comment]
> I guess it is. you can try to build yourself with a newer node version, change two places with `node:22-slim` , I don't have your system, if it works, A pull request is highly welcomed.
> 
> `https://github.com/zilliztech/attu/blob/main/Dockerfile`
How do I package and build? Do I need to use git clone on the server and modify the content before packaging and building?

**Comment by shanghaikid** [comment]
1. clone the repo
2. go to the repo folder
3. yarn install
4. modify the dockerfile
5. run `docker build --tag your-local-tag --file Dockerfile . `

**Comment by 1850772210** [comment]
> 1. clone the repo
> 2. go to the repo folder
> 3. yarn install
> 4. modify the dockerfile
> 5. run `docker build --tag your-local-tag --file Dockerfile . `

thank you very much

**Comment by 1850772210** [comment]
> 1. clone the repo
> 2. go to the repo folder
> 3. yarn install
> 4. modify the dockerfile
> 5. run `docker build --tag your-local-tag --file Dockerfile . `
When building the image, an error occurred in the login dockerhub step: Username and password required. I would like to ask you how to configure it

**Comment by shanghaikid** [comment]
> > 1. clone the repo
> > 2. go to the repo folder
> > 3. yarn install
> > 4. modify the dockerfile
> > 5. run `docker build --tag your-local-tag --file Dockerfile . `
> >    When building the image, an error occurred in the login dockerhub step: Username and password required. I would like to ask you how to configure it

why? you just build the image, you don't push one, you can just enter the username and password of you dockerhub account. but I don't think you need it...

**Comment by 1850772210** [comment]
> why? you just build the image, you don't push one, you can just enter the username and password of you dockerhub account. but I don't think you need it...
I directly built the image on the server, but in the 8th step RUN yard install -- network timeout 1000000, the problem of node unable to create threads still occurs. The following is the error code: Step 8/25: RUN yard install -- network timeout 1000000
---> Running in 711f58cd4ed5
#  node[7]: std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start() at ../ src/node_platform.cc:68
#  Assertion failed: (0) == (uv_thread_create(t.get(),  start_thread, this))
----- Native stack trace -----
1: 0xf73f87 node::Assert(node::AssertionInfo const&) [node]
2: 0x10009ce node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [node]
3: 0x1000aac node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
4: 0xf25841  [node]
5: 0xf26edc node::Start(int, char**) [node]
6: 0x7f9d9a2ef24a  [/lib/x86_64-linux-gnu/libc.so.6]
7: 0x7f9d9a2ef305 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
8: 0xe6d3be _start [node]
Aborted (core dumped)
The command '/bin/sh -c yarn install --network-timeout 1000000' returned a non-zero code: 134

**Comment by 1850772210** [comment]
> why? you just build the image, you don't push one, you can just enter the username and password of you dockerhub account. but I don't think you need it...

I directly built the image on the server, but in the 8th step RUN yard install -- network timeout 1000000, the problem of node unable to create threads still occurs. The following is the error code: Step 8/25: RUN yard install -- network timeout 1000000
---> Running in 711f58cd4ed5
#  node[7]: std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start() at ../ src/node_platform.cc:68
#  Assertion failed: (0) == (uv_thread_create(t.get(),  start_thread, this))
----- Native stack trace -----
1: 0xf73f87 node::Assert(node::AssertionInfo const&) [node]
2: 0x10009ce node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [node]
3: 0x1000aac node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
4: 0xf25841  [node]
5: 0xf26edc node::Start(int, char**) [node]
6: 0x7f9d9a2ef24a  [/lib/x86_64-linux-gnu/libc.so.6]
7: 0x7f9d9a2ef305 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
8: 0xe6d3be _start [node]
Aborted (core dumped)
The command '/bin/sh -c yarn install --network-timeout 1000000' returned a non-zero code: 134

**Comment by shanghaikid** [comment]
can you try this method ? 

https://github.com/nodejs/node/issues/43064#issuecomment-1973209378

**Comment by 1850772210** [comment]
> can you try this method ?
> 
> [nodejs/node#43064 (comment)](https://github.com/nodejs/node/issues/43064#issuecomment-1973209378)

I am very grateful to you. This successfully solved the problem of node not being able to create threads, and now attu is running

**Comment by 1850772210** [comment]
Use --security-opt seccomp=unconfined in docker run command.  可以解决以上问题

**Comment by 1850772210** [comment]
Use --security-opt seccomp=unconfined in docker run command. Can solve the problem of the node mentioned in the title
