### ISSUE TITLE
java sdk v2 createIndex  createCollection  hnsw index  attu不显示 M和efConstruction 参数

### ISSUE THREAD

**Issue by heyufeng666888** [zilliztech/attu#662]
List<IndexParam> indexes = new ArrayList<>();
        // 向量索引
        Map<String, Object> extraParams = new LinkedHashMap<>();
        extraParams.put("M", 16);
        extraParams.put("efConstruction", 128);
        IndexParam vectorIndex = IndexParam.builder()
                .fieldName(VECTOR_FIELD)
                .indexType(IndexParam.IndexType.HNSW)
                .indexName(VECTOR_FIELD)
                .extraParams(extraParams)
                .metricType(IndexParam.MetricType.IP)
                .build();
        indexes.add(vectorIndex);

        clientV2.createIndex(CreateIndexReq.builder()
                .collectionName(COLLECTION_NAME)
                .indexParams(indexes)
                .build());

**Comment by shanghaikid** [comment]
什么版本的attu？

**Comment by heyufeng666888** [comment]
2.3.10 2.4.8 都不行

**Comment by shanghaikid** [comment]
用attu建一个索引可以吗？

**Comment by heyufeng666888** [comment]
使用attu创建 是可以显示的  v1接口也能显示

**Comment by shanghaikid** [comment]
我感觉是v2接口的问题。。。  v2有describeIndex吗？ 看看能拿到数据吗？

**Comment by heyufeng666888** [comment]
有  能显示 索引参数

**Comment by shanghaikid** [comment]
那么神奇吗。。。 我下周测试一下。。

**Comment by yhmo** [comment]
这是java sdk的bug，上周五发布的java sdk v2.4.5已经修复了这个问题。
https://github.com/milvus-io/milvus-sdk-java/issues/1087
