### ISSUE TITLE
Load balancing issue: ForbiddenError: Can not find your connection, please check your connection settings

### ISSUE THREAD

**Issue by guiguan** [zilliztech/attu#668]
**Describe the bug:**
Attu works perfectly fine until we attempt to create more than one replica for HA purposes. The load balancer assigns each request to a random replica, which disrupts the local cache-based authentication (when requests from the same user hit different replicas) and results in the following error:

ForbiddenError: Cannot find your connection, please check your connection settings.

Is there any way we can make the connection sticky? For example, by using consistent hashing on the milvus-client-id header. However, we need the header to be available on the initial requests as well.

**Steps to reproduce:**
1. create more than one replicas behind a reverse proxy
2. visit Attu

**Attu version:**
v2.4.8

**Comment by shanghaikid** [comment]
I will try to find a solution.

**Comment by shanghaikid** [comment]
Client -> Server -> create GRPC client -> response -> Client

I don't think it is easy to share the GRPC client and bunch of states between two attu servers. 

unless I get rid of the node grpc Client, using milvus's restful API, but some of the features are not supported yet.

**Comment by guiguan** [comment]
True. How about making client requests sticky so that the same client ID always goes to the same server replica? Is it possible to generate a client ID in the browser and send it with all requests to the server? In that way, we can config the LB/reverse proxy to route based on client ID

**Comment by shanghaikid** [comment]
![image](https://github.com/user-attachments/assets/921bb6c3-37d8-41a2-9a9a-b4fbaf9586e5)

There is an id in the header, is that enough?

**Comment by shanghaikid** [comment]
> @shanghaikid this ID is only returned and available after `connect`, which establishes the client cache that is needed for authentication. The subsequent requests might be routed to a different replica and miss hitting the cache, and therefore throws that 403 error

Oh, I see, we can generate the ID from client side.

**Comment by shanghaikid** [comment]
Although we can generate the id from the client side, I don't think your replica is going to work, because the id is just used for creating the GRPC client on connection, and the grpc client is stored in memory,  you only have the replica of attu server, not the memory.

**Comment by guiguan** [comment]
Each replica has its own client cache, right? From last time when I was reading your code, that cache is used to validate connection as well. This is independent from other replicas. If we can route each ID to its dedicated replica, it should work?

**Comment by guiguan** [comment]
https://github.com/zilliztech/attu/blob/main/server/src/middleware/index.ts#L39

**Comment by shanghaikid** [comment]
I know, I just don't know how do you build the replica that contains the client cache.

**Comment by guiguan** [comment]
The first connect request with the client ID will build the client cache for the ID?

**Comment by shanghaikid** [comment]
> The first connect request with the client ID will build the client cache for the ID?

Yes.  attu supports connecting to multiple milvus servers.  When a new `connect` request comes in, attu will create a new GRPC client and store it in the cache.

**Comment by guiguan** [comment]
If you generate the client id before the `connect` for each browser, all requests can be routed to the same replica with the correct client cache, right?

**Comment by shanghaikid** [comment]
I don't think it is easy to do the replication for attu server.   The server is stateful, and also we have web socket service inside as well, which is not easy to do so as well. 

If you want to achieve this, it will be a big architecture change, I don't think this is the close target right now.

**Comment by guiguan** [comment]
Na, I am not saying to replicate the memory state of each attu instance (replica), but rather let each of them run independently. We just need to make sure requests for each client ID be routed to the same attu instance. This can be easily achieved by consistent hashing the client ID header, e.g. https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-ConsistentHashLB

> If you generate the client id before the connect for each browser, all requests can be routed to the same replica with the correct client cache, right?

do you mean this needs a big arch change from your side?

**Comment by shanghaikid** [comment]
> Na, I am not saying to replicate the memory state of each attu instance (replica), but rather let each of them run independently. We just need to make sure requests for each client ID be routed to the same attu instance. This can be easily achieved by consistent hashing the client ID header, e.g. https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-ConsistentHashLB
> 
> > If you generate the client id before the connect for each browser, all requests can be routed to the same replica with the correct client cache, right?
> 
> do you mean this needs a big arch change from your side?

Yes we can generate a clientID when the user open attu from the browser
- if clientID is not exist in the local storage, create one
- store the clientID in the local storage
- send connect request with the clientID

This is not a big change. but I don't understand why this is useful, I mean that the Attu server is stateful. You can't load balance stateful backend service.

**Comment by guiguan** [comment]
We can. It is working like sharding or partitioning. Each replica takes care of a subset of all clients

**Comment by shanghaikid** [comment]
> We can. It is working like sharding or partitioning. Each replica takes care of a subset of all clients

I am still thinking it is not going to work, it's not just http requests, we have websocket connections. you can't send data to the same client ID.

**Comment by guiguan** [comment]
WebSocket can be routed to the same replica based on client ID as well. After upgrade, the socket connection will be sticky automatically

**Comment by igoso** [comment]
i meet the same case, when  i downgrade my attu to v2.4.1 which exactly same with milvus.  I installed milvus and attu with docker-compose.
`  attu:
    container_name: milvus-attu
    image: zilliz/attu:v2.4.1
    # environment:
    #   MILVUS_URL: standalone:19530
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/attu:/var/
    depends_on:
      - standalone
    ports:
      - "18000:3000"`

**Comment by LeoNumber1** [comment]
thank you, it works in attu v2.4.1

**Comment by shanghaikid** [comment]
@guiguan could you please try the dev version? `docker pull zilliz/attu:dev`

**Comment by guiguan** [comment]
Awesome, will try tomorrow

**Comment by guiguan** [comment]
@shanghaikid is it possible for you to produce an ARM version of zilliz/attu:dev? we are running our workloads on ARM CPUs

**Comment by guiguan** [comment]
@shanghaikid nvm, we manage to test the x86 zilliz/attu:dev. It is not working. The `milvus-client-id` HTTP header is still not available for `/connect` or `/socket.io` requests

**Comment by shanghaikid** [comment]
> @shanghaikid nvm, we manage to test the x86 zilliz/attu:dev. It is not working. The `milvus-client-id` HTTP header is still not available for `/connect` or `/socket.io` requests

I will update some code logic today.

**Comment by shanghaikid** [comment]
You can try the dev version. 

For http request, the header is there
![image](https://github.com/user-attachments/assets/fb5ad8ea-8b96-4246-afa1-32f4a2de62da)

For the socket connection, there is no way to add the header on the browser, so I added it as the query string , like this
`ws://localhost:3001/socket.io/?milvus-client-id=vwoinl&EIO=4&transport=websocket&sid=m7GkykuDJzumjlbrAAAC
`

**Comment by guiguan** [comment]
@shanghaikid nice. I think it works. I configured the following DestinationRule for an Attu deployment with 3 replicas:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: milvus-attu
  namespace: milvus
spec:
  host: cluster-milvus-attu.milvus.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: milvus-client-id
```

It can route all traffic for a client ID to a fixed replica. For some reason, `/socket.io` requests also have the `milvus-client-id` header set. Did you figure it out on how to set the HTTP header for the websocket connections?

**Comment by shanghaikid** [comment]
> @shanghaikid nice. I think it works. I configured the following DestinationRule for an Attu deployment with 3 replicas:
> 
> 
> 
> ```yaml
> 
> apiVersion: networking.istio.io/v1alpha3
> 
> kind: DestinationRule
> 
> metadata:
> 
>   name: milvus-attu
> 
>   namespace: milvus
> 
> spec:
> 
>   host: cluster-milvus-attu.milvus.svc.cluster.local
> 
>   trafficPolicy:
> 
>     loadBalancer:
> 
>       consistentHash:
> 
>         httpHeaderName: milvus-client-id
> 
> ```
> 
> 
> 
> It can route all traffic for a client ID to a fixed replica. For some reason, `/socket.io` requests also have the `milvus-client-id` header set. Did you figure it out on how to set the HTTP header for the websocket connections?

Yes, I set the header, it just can't be seen on the browser, you can see it from node environment or other backends.

**Comment by guiguan** [comment]
Any plan to release a new version including this soon? This issue can be closed now

**Comment by shanghaikid** [comment]
> Any plan to release a new version including this soon? This issue can be closed now

I  will release one by the end of today.

**Comment by shanghaikid** [comment]
new version released.

**Comment by guiguan** [comment]
@shanghaikid the new version works fine but when trying to explorer data in the `Data` tab of a collection, we got a white screen with following error:

<img width="1368" alt="Screenshot 2024-11-13 at 10 36 01 AM" src="https://github.com/user-attachments/assets/98637296-5d4d-424f-b0e7-47fc4876a476">

**Comment by shanghaikid** [comment]
> @shanghaikid the new version works fine but when trying to explore data in the `Data` tab of a collection, we got a white screen with following error:
> 
> <img alt="Screenshot 2024-11-13 at 10 36 01 AM" width="1368" src="https://private-user-images.githubusercontent.com/940189/385506087-98637296-5d4d-424f-b0e7-47fc4876a476.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NjIzMTUsIm5iZiI6MTczMTQ2MjAxNSwicGF0aCI6Ii85NDAxODkvMzg1NTA2MDg3LTk4NjM3Mjk2LTVkNGQtNDI0Zi1iMGU3LTQ3ZmM0ODc2YTQ3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QwMTQwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWVlNjliODFiNTlhNTFjYjM1YTEyZjM1NDc2NDMwYjFmZGQ1NDhmOTk0MDk0N2Q1YjlkYWQzNDdjNThmNmJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ws0Fr5Syg1TYxW_HT6xrwnwYLK-0qfLojxWAUUyOsj0">
> We can confirm that v2.4.9 doesn't have this issue

can you show me your schema?

**Comment by guiguan** [comment]
@shanghaikid 

<img width="1613" alt="Screenshot 2024-11-13 at 1 24 49 PM" src="https://github.com/user-attachments/assets/0f775779-1ccf-4369-9234-2784c307e2c4">

**Comment by shanghaikid** [comment]
> @shanghaikid
> 
> <img alt="Screenshot 2024-11-13 at 1 24 49 PM" width="1613" src="https://private-user-images.githubusercontent.com/940189/385560015-0f775779-1ccf-4369-9234-2784c307e2c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODU2MjYsIm5iZiI6MTczMTQ4NTMyNiwicGF0aCI6Ii85NDAxODkvMzg1NTYwMDE1LTBmNzc1Nzc5LTFjY2YtNDM2OS05MjM0LTI3ODRjMzA3ZTJjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QwODA4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWZmYmQ1ZDI2YzQ0Mzg5ZGY0NWEzZGU2NTlkZDkzNmYwYTkzZGFmY2RkMDEwMDRkMjEyYjQ2ZDFkZTk3NmRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3U3XNXNUAILUTVHkjoMZfl1XHykdi9g0bZ1oZOXIrkE">

New version released for this issue, thank you for you contribution.

**Comment by guiguan** [comment]
The new version works nicely. Thanks

**Comment by iamcodingcat** [comment]
@shanghaikid cc. @guiguan @LeoNumber1 

I encountered this same issue. But I don't use service mash like `istio`. 
And I try to attu version `v2.4.1` but the error still occurs.

We must operator attu server as only one replicaset? Or, in the future, the fix will be released?
