### ISSUE TITLE
When on K8s, use service address to connet

### ISSUE THREAD

**Issue by yovelcohen** [zilliztech/attu#68]
Today when I'm trying to connect to Attu, I'm using an IP address and port.
that's not a very good solution when it comes to a milvus cluster running on K8s, especially when using the milvus operator and not the helm charts.

I'm not able to connect to milvus when running a cluster using the IP address ( I tried the proxy service's IP adress).
anyways, I think that using the service address should be supported:
if I have a service address like:
```
milvus.default.svc.cluster.local:19530
```

there's no reason using it in my micro services (using milvus python sdk) will work, but not with attu.

**Comment by nameczz** [comment]
@Bennu-Li  any idea?

**Comment by mausch** [comment]
I'm using Attu v2.1.0 and this works for me.
@yovelcohen `milvus.default.svc.cluster.local` points to the `default` namespace, are you sure you installed Milvus in that namespace?

**Comment by yovelcohen** [comment]
It's indeed working with 2.1, before an explicit IP must have been provided.

**Comment by nameczz** [comment]
@yovelcohen 
Sorry forgot to tip here. Yes, we don't need an explicit IP  in attu:v2.1.0.
