### ISSUE TITLE
query结果无法选择单项删除

### ISSUE THREAD

**Issue by kou998** [zilliztech/attu#69]
**Describe the bug:**
1、点击query结果单选框，会选中所有结果。
2、点击一条query结果的单选框，后执行删除，接口响应OK，但无法删除数据
3、全选query结果，执行删除，无法删除数据

**Steps to reproduce:**
1.从左侧collection菜单进入，选择一个collection，load到内存
2.在选择的collection详情界面，输入query条件，点击Query
3.点击query结果其中一条的选择框
4.点击左上方删除图标

**Attu version:**
2.0.1

**Comment by shanghaikid** [comment]
@nameczz Was this issue fixed in 2.0.5?
