### ISSUE TITLE
最新包在 Mac m4 机器中直接提示包损坏，无法打开

### ISSUE THREAD

**Issue by code2tan** [zilliztech/attu#697]
最新包（2.4.11） Mac m4 机器直接打不开，说包损坏：
<img width="256" alt="截屏2024-11-16 23 43 11" src="https://github.com/user-attachments/assets/534dbd83-13bb-4214-a3b3-b13310131ede">
2.4.10包也测试了一下，同样的问题，
windows平台能正常打开

**Comment by code2tan** [comment]
在ubuntu24.10版本中也无法使用，点击图标无任何报错，但是也无法进入软件。
系统信息：
![image](https://github.com/user-attachments/assets/e92c3921-109f-4889-8580-8b87b02eeecd)
使用apt安装，版本：apt 2.9.8 (amd64)

**Comment by shanghaikid** [comment]
sudo xattr -rd com.apple.quarantine /Applications/attu.app
