### ISSUE TITLE
dynamic replica load

### ISSUE THREAD

**Issue by rere950303** [zilliztech/attu#698]
**Describe the feature:**

Starting from Milvus v2.4.13, we can dynamically change replicas without releasing the collection. It would be great if attu could support this feature as well. - https://milvus.io/docs/release_notes.md#Deprecated-v2413

**Describe a specific use case for the feature:**

we can dynamically adjust the collection's replicas while monitoring the incoming search/query traffic to Milvus. Previously, changing replicas required releasing the collection, which caused service interruption. Now, we can handle traffic changes without any downtime.

**Comment by shanghaikid** [comment]
https://github.com/zilliztech/attu/releases/tag/v2.4.12
