### ISSUE TITLE
attu can not build index metric type of BM25

### ISSUE THREAD

**Issue by xgmeng** [zilliztech/attu#706]
**Describe the bug:**
attu can not build index metric type of BM25

![image](https://github.com/user-attachments/assets/4bb81bf6-6646-47a3-888e-8dd894408dac)

![image](https://github.com/user-attachments/assets/49bf45f6-f594-49af-adaf-a8fd5fa618d1)

**Steps to reproduce:**
1. Build the index through the code (https://milvus.io/docs/zh/full-text-search.md);
2. Delete index at attu;
3. Build the index through attu

**Attu version:** 
V2.4.12

**Milvus version:**
V2.5.0-beta-gpu

**Comment by shanghaikid** [comment]
not supported yet.

**Comment by shanghaikid** [comment]
https://github.com/zilliztech/attu/releases/tag/v2.5.0
