### ISSUE TITLE
Attu cannot connect to milvus k8s cluster

### ISSUE THREAD

**Issue by wutachiang** [zilliztech/attu#71]
The distributed version of milvus deployed by helm, attu is enabled by default. Refer to the official documentation https://milvus.io/cn/docs/v2.0.x/attu_install-helm.md to access cluster services by mapping ports to local. Through port mapping, 127.0.0.1 can access the milvus cluster, and from the cluster server, the milvus service can be accessed through 10.255.196.189. The attu service works by default, but a network error is displayed when adding a milvus connection.

![2022-06-01_09-26](https://user-images.githubusercontent.com/13926708/171309707-48ce96d5-fd6a-4996-82c2-35eb660cc26d.png)
![2022-06-01_00-23](https://user-images.githubusercontent.com/13926708/171227238-0d58308e-ec6f-484b-81c2-7422d862d6f2.png)
![2022-06-01_00-24](https://user-images.githubusercontent.com/13926708/171227254-88e1176e-90fd-41b8-8623-fe6d1bb664b2.png)
![2022-06-01_00-25](https://user-images.githubusercontent.com/13926708/171227285-5a619019-f505-4ddd-b92e-a114e413c6e2.png)

**Comment by nameczz** [comment]
For now, attu need to know the attu server ip address as HOST_URL. Will improve it in next release.

**Comment by nameczz** [comment]
@wutachiang  you can have a try with Attu v2.1.0. We don't need HOST_URL any more.
