### ISSUE TITLE
mac m2芯片 打开attu-mac-arm64-v2.4.12.dmg里面的attu.app提示 已损坏, 打开x64版本的可以正常使用 但是感觉速度很慢

### ISSUE THREAD

**Issue by 1273082756** [zilliztech/attu#713]
**Describe the bug:**

**Steps to reproduce:**
1.
2.
3.

**Attu version:**

**Attu version:**

**Comment by shanghaikid** [comment]
Mac M chip install app failed: attu.app is damaged and cannot be opened.
  ```sudo xattr -rd com.apple.quarantine /Applications/attu.app```

**Comment by 1273082756** [comment]
个人的解决办法:
先把软件拖到/Application, 然后执行下面的命令就可以了
xattr -cr xattr -cr /Applications/attu.app

**Comment by 1273082756** [comment]
> Mac M chip install app failed: attu.app is damaged and cannot be opened. `sudo xattr -rd com.apple.quarantine /Applications/attu.app`

Thank you for your help. I have found a solution and it is similar to yours.
