### ISSUE TITLE
Vector Search 异常

### ISSUE THREAD

**Issue by hukang6677** [zilliztech/attu#85]
**Describe the bug:**
在没有编辑nprobe参数前点击“Search”按钮，查询结果正常，页面显示正常。
然后修改nprobe参数值，再点击“Search”按钮，有结果列表，但页面提示错误信息如下。
fail to search on all shard leaders, err=fail to Search, QueryNode ID=17, reason=Search 17 failed, reason [UnexpectedError] Assert "adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:54 => [SearchOnSealed]Search params check failed err %!w(<nil>)

**Steps to reproduce:**
1.
2.
3.

**Attu version:**
attu:v2.1.0
**Attu version:**

**Comment by hukang6677** [comment]
![e2b362d5c18a90dc27667fd991903d3](https://user-images.githubusercontent.com/102129512/181140161-e714ec29-4a8c-4b3a-b34c-b79bf53a420b.png)



![c84400b321b75a9456f606a1117e2d4](https://user-images.githubusercontent.com/102129512/181140101-d159f2bc-7615-44a1-871c-5325e90fdf87.png)


![ff98c3a92a94703805137561de7ce0b](https://user-images.githubusercontent.com/102129512/181140188-8c6696ba-9aff-4976-a254-bbd9143b60ae.png)

**Comment by nameczz** [comment]
I can't reproduce this error in my local.
I dont think it's attu bug, may be you should ask in milvus repo why throw this error. @hukang6677 
Thanks.

**Comment by shanghaikid** [comment]
Can't not recreated this issue.
