### ISSUE TITLE
打开Attu 的user菜单栏报错，点击添加用户按钮报错

### ISSUE THREAD

**Issue by WayneLee5991** [zilliztech/attu#86]
**Describe the bug:**
打开Attu 的user菜单栏报错，点击添加用户按钮报错

**Steps to reproduce:**
1.打开软件

2.点击左侧user菜单栏，右上角报错
Error: Error: 12 UNIMPLEMENTED: unknown method ListCredUsers for service milvus.proto.milvus.MilvusService

3.创建新用户时报错
Error: Error: 12 UNIMPLEMENTED: unknown method CreateCredential for service milvus.proto.milvus.MilvusService

**Milvus version:**
v 2.0.2

**Attu version:**
v 2.1.0

**Comment by nameczz** [comment]
user feature and varchar field is only working for Milvus v2.1.0.

**Comment by nameczz** [comment]
Not issue
