### ISSUE TITLE
Entity Count 数据不更新

### ISSUE THREAD

**Issue by hukang6677** [zilliztech/attu#87]
**Describe the bug:**
已经Loaded Collections，正常查询有数据。然后通过JavaSDK 添加数据 milvusClient.insert(insertParam)。再查询也能查出新添加的数据，但 attu页面显示的Entity Count 数量没有加一。还是原来的数量。但在attu页面上查询数据又能查到。

**Steps to reproduce:**
1.
2.
3.

**Attu version:**
attu:v2.1.0
milvus:v2.1.0
**Attu version:**

**Comment by nameczz** [comment]
Is java sdk return the correct entity count? @hukang6677

**Comment by hukang6677** [comment]
java sdk 返回正常，有问题的是下面的显示数据不更新，数据当前应该是1,000,004  但页面一直显示1,000,003
 
![1658884397692_EAA61AE6-8A4A-4669-8323-607947E2C95C](https://user-images.githubusercontent.com/102129512/181139059-69e1e9fb-6b4e-41f7-88d4-90ff300e746a.png)

![1658884495323_22817D40-B9A1-4c2c-A314-4BA7E747A7D8](https://user-images.githubusercontent.com/102129512/181139240-65267cf2-00fe-4a89-ba95-d16f8a541208.png)

但有个现象，我刚刚调用Javasdk ( milvusClient.getCollectionStatistics )这个接口后，attu页面才会同步为1,000,004

**Comment by nameczz** [comment]
If you want to know the entity count immediately, you need to flush after insert data into milvus. 
Otherwise, milvus will flush in future.

**Comment by shanghaikid** [comment]
we add a refresh button on the collection view.
