### ISSUE TITLE
Add interface to view milvus server version

### ISSUE THREAD

**Issue by JackLCL** [zilliztech/attu#94]
**Describe the feature:**
Add interface to view milvus server version

**Describe a specific use case for the feature:**
Only after the user checks the version of the milvus server can they know which version of the sdk to use.

**Comment by nameczz** [comment]
display milvus version in metric page. @Tumao727

**Comment by shanghaikid** [comment]
![image](https://user-images.githubusercontent.com/185051/196154860-39fba6b0-fb96-485b-9f1c-f90935373742.png)
Please update to the latest version.
