### ISSUE TITLE
Page blocking

### ISSUE THREAD

**Issue by KajiMaCN** [zilliztech/attu#96]
**Describe the bug:**
As shown, tapping the icon in the bottom left corner of the node view will cause the page to be obscured

**Steps to reproduce:**
1.
2.
3.

**Attu version:** 2.1.0

**Attu version:** 2.1.0
![image](https://user-images.githubusercontent.com/28567261/190046978-17519eaa-6596-44c8-ac86-a8fa76282f98.png)

**Comment by shanghaikid** [comment]
fixed in the latest version.
